### ISSUE TITLE
Publish java_export target without sources jar

### ISSUE THREAD

**Issue by bertschneider** [bazelbuild/rules_jvm_external#1001]
Is there a way to publish a `java_export` target without its sources jar?

Locally I patched the current version so that targets can be tagged with `no-sources`, similar to `no-javadocs`, but wonder if there's another solution. If you like I can provide that change as PR.

**Comment by shs96c** [comment]
For things like Maven Central, the source jars are required, and there's never been a case where uploading them has been detrimental, but if you have a use case, I'll happily review that PR.

**Comment by bertschneider** [comment]
The use-case is to distribute a close source library/application via an access restricted repository. I created the mentioned (small) PR.
