### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by agluszak** [bazelbuild/rules_jvm_external#1014]
There have been a lot of fixes, especially to the bzlmod part, since the last release. Please release 5.4 with those changes to BCR.

**Comment by shs96c** [comment]
We're working on it! I landed #986 yesterday, which was the major blocker. I'm attempting to get #989 in too, which will add the ability for us to support Maven BOM files too.

Since we're dropping support for Jetifier, we'll likely bump the major version number too.

**Comment by shs96c** [comment]
I've now opened #1021 and [created a milestone](https://github.com/bazelbuild/rules_jvm_external/milestone/2) for this
