### ISSUE TITLE
 ERROR: no such target '//src/test:greeter_test_app': target 'greeter_test_app' not declared in package 'src/test' 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_jvm_external#1015]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3556#018cb373-7013-4915-9d3f-29a0c2c3f313

Platform : [rules_jvm_external - examples (Android instrumentation test example on ](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3556#018cb373-7010-46cf-8042-9d17becdce25):mac:, [rules_jvm_external - examples (Android instrumentation test example on ](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3556#018cb373-7013-4915-9d3f-29a0c2c3f313):windows:

steps:
```
git clone ttps://github.com/bazelbuild/rules_jvm_external.git
git reset 1dd7329412843a45d3694b0774ddcad540e79d1c --hard
export USE_BAZEL_VERSION=30452433de6f98fa2cdd994688edf71066ee2e84
bazel build  -- //src/main:greeter_app //src/test:greeter_test_app
```

Logs:

```
(03:08:17) ERROR: C:/b/bk-windows-knsj/bazel-org-repo-root/rules_jvm_external/examples/android_instrumentation_test/src/test/BUILD:9:1: name 'android_instrumentation_test' is not defined
(03:08:17) ERROR: Skipping '//src/test:greeter_test_app': no such target '//src/test:greeter_test_app': target 'greeter_test_app' not declared in package 'src/test' defined by C:/b/bk-windows-knsj/bazel-org-repo-root/rules_jvm_external/examples/android_instrumentation_test/src/test/BUILD
(03:08:17) ERROR: no such target '//src/test:greeter_test_app': target 'greeter_test_app' not declared in package 'src/test' defined by C:/b/bk-windows-knsj/bazel-org-repo-root/rules_jvm_external/examples/android_instrumentation_test/src/test/BUILD

```

CC Greenteam @SalmaSamy

**Comment by mai93** [comment]
I think this is due to https://github.com/bazelbuild/bazel/commit/2eda429be6523390e75bf0fb55ece62defd08da0. @ajsinclair, is there another version of this rule that can be used?

**Comment by ajsinclair** [comment]
Not currently in open source. The rules_android maintainers may have more input. I think the specific intention of this test is to test the rules against Bazel Head.  If that is the case then this test will have to be removed. The alternative is to pin the test to use some version of Bazel 7. The intention is to [delete all of the native Android Rules for the Bazel 8.0](https://github.com/bazelbuild/rules_jvm_external/issues/1015#issuecomment-1877884537). The android_instrumentation_test rule will not have a corresponding Starlark implementation. There will likely be another rule to take its place but it does not exist yet.
