### ISSUE TITLE
Release `rules_jvm_external` 6.0

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_jvm_external#1021]
[The project is here](https://github.com/bazelbuild/rules_jvm_external/milestone/2)

**Comment by rdesgroppes** [comment]
Just gave `rules_jvm_external` **6.0** a try with bazel **6.4.0**:
```
ERROR: Traceback (most recent call last):
	File "/path/to/external/rules_jvm_external/private/rules/has_maven_deps.bzl", line 1, column 37, in <toplevel>
		load("@rules_java//java:defs.bzl", "JavaInfo")
Error: file '@rules_java//java:defs.bzl' does not contain symbol 'JavaInfo'
```

**Comment by odisseus** [comment]
I just got this error when attempting to use the version 6.0:
```
An error occurred during the fetch of repository 'rules_jvm_external':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/3f57bb81dd178514a6db80432bcb53b1/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_jvm_external/archive/6.0.zip] to /root/.cache/bazel/_bazel_root/3f57bb81dd178514a6db80432bcb53b1/external/rules_jvm_external/temp10206693494710760252/6.0.zip: Checksum was c44568854d8bb92fe0f7dd6b1e8957ae65e45e32a058727fcf62aaafbd36f17b but wanted 85fd6bad58ac76cc3a27c8e051e4255ff9ccd8c92ba879670d195622e7c0a9b7
```

**Comment by shs96c** [comment]
I can look into the checksum problem, since that should be correct. I'll check

**Comment by shs96c** [comment]
@rdesgroppes, it's possible the version of `rules_java` you're using isn't the one that `rules_jvm_external` has been built with. What does `bazel query --output=build //external:rules_java` show? Does it show that `rules_java` was loaded from `rules_jvm_external`'s dependencies, or from something else?

**Comment by shs96c** [comment]
@odisseus, I've checked, and the shasum for the repo, as listed on the releases page, is correct:

```curl -L https://github.com/bazelbuild/rules_jvm_external/releases/download/6.0/rules_jvm_external-6.0.tar.gz | shasum -a256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4532k  100 4532k    0     0  7018k      0 --:--:-- --:--:-- --:--:-- 7018k
85fd6bad58ac76cc3a27c8e051e4255ff9ccd8c92ba879670d195622e7c0a9b7  -
```

I suspect you're not using the URL we give in the release, but instead are using the archive that GitHub can automatically generate. We switched from those auto-generated archives to ones we build manually because GitHub sometimes change how those archives are packed, which changes the checksum.

Can you please check which URL you're downloading from?

**Comment by odisseus** [comment]
Yes, you are right. I forgot to update the download link.

**Comment by rdesgroppes** [comment]
> @rdesgroppes, it's possible the version of `rules_java` you're using isn't the one that `rules_jvm_external` has been built with. What does `bazel query --output=build //external:rules_java` show? Does it show that `rules_java` was loaded from `rules_jvm_external`'s dependencies, or from something else?

@shs96c it says:
```
$ bazel query --output=build //external:rules_java
ERROR: Traceback (most recent call last):
	File "/path/to/external/rules_jvm_external/private/rules/has_maven_deps.bzl", line 1, column 37, in <toplevel>
		load("@rules_java//java:defs.bzl", "JavaInfo")
Error: file '@rules_java//java:defs.bzl' does not contain symbol 'JavaInfo'
ERROR: Error computing the main repository mapping: at /path/to/maven/init.bzl:1:6: at /path/to/external/rules_jvm_external/defs.bzl:17:6: initialization of module 'private/rules/has_maven_deps.bzl' failed
 checking cached actions
```

**Comment by shs96c** [comment]
That's some really strange output. There should be nothing in that query that causes us to load `has_maven_deps.bzl`, so the error you're seeing is surprising. We've tested `rules_jvm_external` with `rules_java` 6.5.2, so you could try adding this at the top of your `WORKSPACE` file:

```starlark
http_archive(
    name = "rules_java",
    urls = [
        "https://github.com/bazelbuild/rules_java/releases/download/6.5.2/rules_java-6.5.2.tar.gz",
    ],
    sha256 = "16bc94b1a3c64f2c36ceecddc9e09a643e80937076b97e934b96a8f715ed1eaa",
)
```

It needs to be the first thing you load so that we can force that version to be used. That version [definitely exports the expected symbol](https://github.com/bazelbuild/rules_java/blob/6.5.2/java/defs.bzl#L152).

The other thing to check is that you're setting up `rules_jvm_external` using a stanza that looks like this in your `WORKSPACE` file after you've loaded it via `http_archive`:

```starlark
http_archive(
    name = "rules_jvm_external",
    ...  # The other details from the `releases` page
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()
```

These two entries weren't as required in older releases, so if you've been upgrading `rules_jvm_external` in your repo for a while you may not have them in there already, but the dependency on `rules_java` now makes this an essential step in setting up `rules_jvm_external`.

**Comment by rdesgroppes** [comment]
@shs96c I just managed to get it working by moving all lines dealing with `rules_jvm_external` prior to `rules_proto`/`rules_proto_grpc`-related lines.

**Comment by shs96c** [comment]
Glad to hear it's working for you now. This kind of ordering of loads of dependencies is always a real pain to track down.
