### ISSUE TITLE
Can't install maven dependencies with a top-level "build" directory on case-insensitive filesystems

### ISSUE THREAD

**Issue by alex-shinn** [bazelbuild/rules_jvm_external#1028]
Currently it's impossible to import protovalidate (https://mvnrepository.com/artifact/build.buf/protovalidate/0.1.9) on OSX because that repository contains a top-level "build" directory as part of the package path, which conflicts with the generated "BUILD" file.  Trying results in the error:

```
ERROR: An error occurred during the fetch of repository 'build_buf_protovalidate_0_1_9':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_tkanda/7710aed0b0cdc40a869d8ca35bc8abd7/external/bazel_tools/tools/build_defs/repo/http.bzl", line 183, column 13, in _http_file_impl
		ctx.file("file/BUILD", _HTTP_FILE_BUILD.format(downloaded_file_path))
Error in file: java.io.IOException: /private/var/tmp/_bazel_tkanda/7710aed0b0cdc40a869d8ca35bc8abd7/external/build_buf_protovalidate_0_1_9/file/BUILD (Directory not empty)
```

I believe this stems from the hard-coded "BUILD" filename in: https://github.com/bazelbuild/rules_jvm_external/blob/80ce39ad50ed49c00ca7cd26e66107fbbde98483/coursier.bzl#L622

It should be fine to just replace the filename with BUILD.bazel (see https://github.com/bazelbuild/bazel/issues/4517).  Alternatively, we could do this only on OSX, or more conservatively only if a given flag is specified.

**Comment by alex-shinn** [comment]
Actually, it looks like this error is coming from `_http_file_impl` in core bazel, though we probably need to fix both places.

**Comment by cheister** [comment]
Interesting, I'm not surprised that the `build` package is creating a conflict.  

I realize it's not ideal but I think you could workaround this for now by downloading the jar in your WORKSPACE with something like
```
http_file(
    name = "build_buf_protovalidate_0_1_9",
    sha256 = "d9c141bb6172c3a42283bde148f369772014d79bffc0f243a1da73b9da84e213",
    url = "https://repo.maven.apache.org/maven2/build/buf/protovalidate/0.1.9/protovalidate-0.1.9.jar",
)
```

and then set up a jvm_import rule in a BUILD file

```
load("@rules_jvm_external//private/rules:jvm_import.bzl", "jvm_import")

jvm_import(
    name = "build_buf_protovalidate",
    jars = ["build/buf/protovalidate/0.1.9/protovalidate-0.1.9.jar"],
    tags = [
        "maven_coordinates=build.buf:protovalidate:0.1.9",
        "maven_repository=https://maven.global.square/artifactory/square-public/",
        "maven_sha256=d9c141bb6172c3a42283bde148f369772014d79bffc0f243a1da73b9da84e213",
        "maven_url=https://maven.global.square/artifactory/square-public/build/buf/protovalidate/0.1.9/protovalidate-0.1.9.jar",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_github_seancfoley_ipaddress",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:jakarta_mail_jakarta_mail_api",
        "@maven//:org_projectnessie_cel_cel_core",
    ],
)

alias(
    name = "build_buf_protovalidate_0_1_9",
    actual = "build_buf_protovalidate",
    visibility = ["//visibility:public"],
)

genrule(
    name = "build_buf_protovalidate_0_1_9_extension",
    srcs = ["@build_buf_protovalidate_0_1_9//file"],
    outs = ["build/buf/protovalidate/0.1.9/protovalidate-0.1.9.jar"],
    cmd = "cp $< $@",
    visibility = ["@@//visibility:private"],
)
```

It means you have to declare all of the protovalidate dependencies in your maven_install rule so you can refer to them as deps, but it should let you use the protovalidate jar.

**Comment by cheister** [comment]
Actually, after looking at it, I think we can fix this just by changing the downloaded_file_path used with http_file when it has a `build` directory at the top-level https://github.com/bazelbuild/rules_jvm_external/pull/1037

**Comment by cheister** [comment]
Fixed with https://github.com/bazelbuild/rules_jvm_external/pull/1037

**Comment by alex-shinn** [comment]
Thanks!
