### ISSUE TITLE
With `bzlmod` if the root module and a dependency both specify a lock file, use the root module's

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_jvm_external#1035]
Rulesets like `protobuf` need to add to the default namespace (`maven`) when using `bzlmod`. For their own tests, they'd like to use a lock file, but if they specify one, then currently `rules_jvm_external` will fail the build, since there will be conflicting lock files if the user also uses a lock file in the default namespace.

To work around this, if there's a lock file in the root module for a particular namespace, _always_ use that in preference to the one from another ruleset. If two rulesets both want a lock file that _isn't_ in the root namespace, then fail the build.

**Comment by SanjayVas** [comment]
> Rulesets like `protobuf` need to add to the default namespace (`maven`) when using `bzlmod`. 

Is this true? At least from the warnings that are output by the module extension, it looks like it wants each Bazel module to use a different Maven repo name ("namespace" in your terms). This would imply that only the leaf module is free to use the default namespace.

**Comment by shs96c** [comment]
This is true. The way that different rulesets contribute to shared workspaces (eg. the default `maven` one) in the `bzlmod` world is to have their own `maven.install` which adds the items they need. `rules_jvm_external` will gather and merge all of these into a single set of artifacts that need resolving.

The example of `protobuf` is a good one: when you're using protobuf, you want to use the correct version of the java dependencies, and (I hope) that's what it's contributing.

**Comment by SanjayVas** [comment]
From https://github.com/bazelbuild/rules_jvm_external/blob/4b77656fa533a835759c992a2f0781239e909a50/private/extensions/maven.bzl#L216C4-L217C85:

> This will allow us to warn users when more than module attempts to update a maven repo (which is normally undesired behaviour)

> The example of `protobuf` is a good one: when you're using protobuf, you want to use the correct version of the java dependencies, and (I hope) that's what it's contributing.

This is the problem I raised in #995, but I didn't get any responses to.
