### ISSUE TITLE
Exclusion syntax for MODULE.bazel files?

### ISSUE THREAD

**Issue by ekohlwey** [bazelbuild/rules_jvm_external#1052]
Is there an exclusion syntax for MODULE.bazel files?

The source of this question is an attempt to apply the workaround for a cyclic dependency in the grpc-java libraries documented here https://github.com/grpc/grpc-java/issues/10576.

**Comment by shs96c** [comment]
There are two methods for excluding artifacts when using `bzlmod`. The first is a global exclusion available on the `install` tag, and you can specify specific exclusions for specific targets using the `artifact` tag. There is [documentation available here](https://github.com/bazelbuild/rules_jvm_external/blob/master/docs/bzlmod.md#artifact-exclusion).
