### ISSUE TITLE
`use_repo_rule` usage breaks Bazel 5/6 support

### ISSUE THREAD

**Issue by luispadron** [bazelbuild/rules_jvm_external#1055]
`use_repo_rule` is currently only in Bazel 7+ and `rules_jvm_external` 6.0 uses this. It causes the following failure:

```
ERROR: https:/bcr.bazel.build/modules/rules_jvm_external/6.0/MODULE.bazel:65:13: name 'use_repo_rule' is not defined
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> rules_jvm_external@6.0: error executing MODULE.bazel file for rules_jvm_external@6.0
```

**Comment by shs96c** [comment]
This is a known issue, and why the `bzlmod` section of the release notes starts with `If you are using Bazel 7 or above`.

Since Bazel 7 is the latest LTS, `bzlmod` behaviour changed between the 6.5.0 and 7.0.0, and the previous WORKSPACE-based approach still works, we won't be making changes.
