### ISSUE TITLE
Failed to resolve deps for com.google.firebase:firebase-analytics:aar:21.5.0

### ISSUE THREAD

**Issue by oliviernotteghem** [bazelbuild/rules_jvm_external#1057]
Steps to reproduce:
- Reuse [simple example](https://github.com/bazelbuild/rules_jvm_external/tree/master/examples/simple) 
- Edit WORKSPACE file, add "com.google.firebase:firebase-analytics:aar:21.5.0" to the artifact list.
- Edit BUILD file to add "@maven//:com_google_firebase_firebase_analytics" to deps of target
- Run :  bazel build :my_app

Result:
```
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_oliviern/dd52b20a76c39eca281d5f4cd222340b/external/rules_jvm_external/coursier.bzl", line 949, column 38, in _coursier_fetch_impl
		dep_tree = make_coursier_dep_tree(
	File "/private/var/tmp/_bazel_oliviern/dd52b20a76c39eca281d5f4cd222340b/external/rules_jvm_external/coursier.bzl", line 882, column 13, in make_coursier_dep_tree
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Error fetching artifacts:
https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar: not found: https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar

ERROR: /Users/oliviern/Uber/rules_jvm_external/examples/simple/WORKSPACE:21:14: fetching coursier_fetch rule //external:maven: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_oliviern/dd52b20a76c39eca281d5f4cd222340b/external/rules_jvm_external/coursier.bzl", line 949, column 38, in _coursier_fetch_impl
		dep_tree = make_coursier_dep_tree(
	File "/private/var/tmp/_bazel_oliviern/dd52b20a76c39eca281d5f4cd222340b/external/rules_jvm_external/coursier.bzl", line 882, column 13, in make_coursier_dep_tree
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Error fetching artifacts:
https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar: not found: https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar

ERROR: Error computing the main repository mapping: no such package '@@maven//': Error while fetching artifact with coursier: Error fetching artifacts:
https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar: not found: https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar
```

Note : 
https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar does not exist
https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.aar does exist

Looks like gradle is falling back to consuming .aar when .jar is missing.

**Comment by Bencodes** [comment]
I believe this is the same issue as https://github.com/bazelbuild/rules_jvm_external/issues/909 but with a different artifact.

**Comment by oliviernotteghem** [comment]
The key to troubleshoot this is to enable verbose mode in jvm_rules_external, obtain coursier args, replay coursier command with 'resolve' action and --tree param. 

Example : /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java -noverify -jar /private/var/tmp/_bazel_oliviern/dd52b20a76c39eca281d5f4cd222340b/external/maven/coursier resolve "com.google.firebase:firebase-analytics:21.5.0,type=aar"  --verbose --no-default  --checksum SHA-1,MD5 --repository https://maven.google.com --repository https://repo1.maven.org/maven2 --cache v1 --tree

Conclusion : starting with version > 20.4.0, com.google.firebase:firebase-common-ktx is wrongly published and specify a jar dependency that doesn't exist (firebase-component).

Fix : file github issue to Google to fix their POM in future versions

Temp : pin version 20.4.0 (i.e explicitly add coord to WORKSPACE so that it takes precedences on 20.4.1 or 20.4.2).

**Comment by shs96c** [comment]
This doesn't look like a `rules_jvm_external` issue, so I shall close this. Please let me know if you'd like me to reopen it.

**Comment by oliviernotteghem** [comment]
We might want to have same behavior as Gradle : when POM incorrectly specifies a JAR instead of AAR, it will fallback to using the AAR. Thoughts?
