### ISSUE TITLE
Implement global exclusion for artifacts

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_jvm_external#110]
Related: https://github.com/coursier/coursier/issues/1122

Currently, we support artifact exclusions using the `maven.artifact(exclusions = [...])` helper. This feeds the `group:artifact` coordinates into a `--local-exclude-file` for Coursier CLI. 

The problem with this is that if artifact A excludes B from its transitive dependencies, and C also depends on B but doesn't exclude it, B will still be fetched into the transitive dependencies on A. This can be confusing and will lead to complex `maven_install` declarations since every artifact that transitively depends on B will need to exclude it. 

Coursier CLI supports another flag called `--exclude`, which is basically a global exclude. I propose to add another top level `exclusions` attribute to `maven_install`, that simply feeds this collection of `group:artifact` into the CLI `--exclude` option.

The alternative is to take the per-artifact exclusions and feed them into `--exclude`, but this breaks the API affinity between `maven_install` and Coursier CLI, and can be even more confusing down the road.

More discussion from Bazel Slack: https://bazelbuild.slack.com/archives/CDCE4DFAP/p1555009607029700

cc @dkelmer

**Comment by mpassell** [comment]
Agreed on your last point. With luck, this will just be a problem to work around in the short- to medium-term. In the meantime, treating local exclusions as global would surprise/confuse me if I didn't have this context.
