### ISSUE TITLE
Add a bzlmod extension to override default repositories

### ISSUE THREAD

**Issue by darkrift** [bazelbuild/rules_jvm_external#1150]
In an environment that restricts the usage of public repositories and requires the usage of an internal repository (such as artifactory), it is quite cumbersome to specify the repositories attribute on every maven.install.

Ideally, we would have something along the lines of the following snippet to allow to override the DEFAULT_REPOSITORIES variable

```
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.default_repositories(
  repositories = [
    "https://internal-repo.domain.org/...",
  ],
)
```

This could then be evaluated as the repositories to use rather than then hardcoded DEFAULT_REPOSITORIES. The hardcoded DEFAULT_REPOSITORIES could still be used as the default value if no `default_repositories` is specified.

You could still add the default if you only need to use your internal repo for your company specific artifacts and still allow to use the public repo for anything already available publicly:
```
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.default_repositories(
  repositories = [
    "https://internal-repo.domain.org/...",
    "https://repo1.maven.org/maven2",
  ],
)
```

**Comment by shs96c** [comment]
You don't need to do this. All you need to do in your root module is to add a `maven.install(name = "workspace-name-to-override", repositories = [...])`

You can also use the [downloader config option](https://blog.aspect.build/configuring-bazels-downloader) to rewrite remote requests. This "things download from unexpected places" problem is exactly what it was designed to solve.

**Comment by darkrift** [comment]
> You don't need to do this. All you need to do in your root module is to add a `maven.install(name = "workspace-name-to-override", repositories = [...])`
> 
> You can also use the [downloader config option](https://blog.aspect.build/configuring-bazels-downloader) to rewrite remote requests. This "things download from unexpected places" problem is exactly what it was designed to solve.

The problem with the maven install is that with various tools usage (openapi generator, libraries for tests which run independently with rules_itest, etc), I'm isolating them from each other and from the "production" code that lives in the monorepo.

I currently have 3 different maven.install and soon to be more.

The downloader config option is one thing but while it looks like a valid option I find it rather non-obvious where your artifacts are coming from when you look at the MODULE.bazel file and you need to know that bazel as such "override" mechanism. Imo, not a great DX. It does address the point for rules that don't have such an override mechanism directly in MODULE.bazel though.
