### ISSUE TITLE
FR: A way to exclude deps from artifacts that are determining the versions from BOMs

### ISSUE THREAD

**Issue by tharakadesilva** [bazelbuild/rules_jvm_external#1162]
I might be wrong, but there isn't a way to add excludes without maven.artifact and maven.artifact requires a version so it seems impossible.

If there is a way, please let me know, I'll submit a PR to update the docs for it.

**Comment by cheister** [comment]
Just to clarify, you want to specify a BOM but exclude some of the versions from that BOM?  Is that a good idea?  Isn't the intention of a BOM to give you all of the versions you need for an artifact?

Is it sufficient to override the version of an artifact after it is included by the BOM?

**Comment by vinnybod** [comment]
I have the same problem, different use case @cheister .
I have a dependency with a version controlled by a bom. But I want it to be a `neverlink` dependency.
According to the docs, I need to do this with `maven.artifact`, but `maven.artifact` requires version as a positional argument, so I'm not sure how to create the `maven.artifact`

```
maven_install(
  ...
  boms = [
    "io.opentelemetry:opentelemetry-bom:1.31.0"
  ],
  artifacts = [
    maven.artifact(group="io.opentelemetry", artifact="opentelemetry-api", version=??, neverlink=True), 
    maven.artifact(group="io.opentelemetry", artifact="opentelemetry-sdk", version=??, neverlink=True), 
  ]
)
```

**Comment by tharakadesilva** [comment]
> Just to clarify, you want to specify a BOM but exclude some of the versions from that BOM? Is that a good idea? Isn't the intention of a BOM to give you all of the versions you need for an artifact?
> 
> Is it sufficient to override the version of an artifact after it is included by the BOM?

Not necessarily, I meant something similar what @vinnybod mentioned, sorry my description wasn't clearer. I meant something like this:

```
maven_install(
  ...
  boms = [
    "io.opentelemetry:opentelemetry-bom:1.31.0"
  ],
  artifacts = [
    maven.artifact(group="io.opentelemetry", artifact="opentelemetry-api", version=??, exclusions = [...]), 
    maven.artifact(group="io.opentelemetry", artifact="opentelemetry-sdk", version=??, exclusions = [...]), 
  ]
)
```

I might need to add exclusions for some things like `commons-logging` (something that we do often) and when we do add the exclusions, we need to explicitly specify the version.

**Comment by cheister** [comment]
Thanks for clarification., I initially misinterpreted the description of the PR.

https://github.com/bazelbuild/rules_jvm_external/pull/1183 should fix this

**Comment by tharakadesilva** [comment]
> Thanks for the clarification., I initially misinterpreted the description of the PR.
> 
> #1183 should fix this

Thank you!!

**Comment by tharakadesilva** [comment]
Tested @cheister submission (https://github.com/bazelbuild/rules_jvm_external/pull/1183) and it is working as expected, closing the ticket.
