### ISSUE TITLE
rules_jvm_external v6.1 creates duplicate jvm_import targets for binary and source JARs

### ISSUE THREAD

**Issue by mbland** [bazelbuild/rules_jvm_external#1189]
rules_jvm_external v6.1 somehow creates duplicate `jvm_import` rules for binary and source jars, instead of using the `srcjar` attribute, in [EngFlow/bazel_invocation_analyzer](https://github.com/EngFlow/bazel_invocation_analyzer).

This happens both before applying the changes from EngFlow/bazel_invocation_analyzer#182 (still using Bazel 7.0.2 and older versions of other Bazel modules and JARs) and after (using the latest Bazel 7.2.1 and the latest versions of other Bazel modules and JARs).

EngFlow/bazel_invocation_analyzer is already relatively small, but I can try to provide a smaller reproduction example if desired.

From the description of that PR, this shows the effect of bumping to v6.1:

```txt
ERROR: Traceback (most recent call last):
  File ".../external/rules_jvm_external~~maven~maven/BUILD",
    line 34, column 11, in <toplevel>
      jvm_import(

Error in jvm_import: jvm_import rule
  'com_google_auto_value_auto_value_annotations' in package ''
  conflicts with existing jvm_import rule, defined at
  .../external/rules_jvm_external~~maven~maven/BUILD:9:11
```

The content of rules_jvm_external~~maven~maven/BUILD at lines 9 and 34 is:

```bzl
jvm_import(
  name = "com_google_auto_value_auto_value_annotations",
  jars = ["com/google/auto/value/auto-value-annotations/1.10.1/auto-value-annotations-1.10.1.jar"],
```

```bzl
jvm_import(
  name = "com_google_auto_value_auto_value_annotations",
  jars = ["com/google/auto/value/auto-value-annotations/1.10.1/auto-value-annotations-1.10.1-sources.jar"],
```

This pattern repeats for all the JAR targets.

The BUILD contents from v5.3, which builds successfully both before and after applying the PR changes:

```bzl
jvm_import(
  name = "com_google_auto_value_auto_value_annotations",
  jars = ["com/google/auto/value/auto-value-annotations/1.10.1/auto-value-annotations-1.10.1.jar"],
  srcjar = "com/google/auto/value/auto-value-annotations/1.10.1/auto-value-annotations-1.10.1-sources.jar",
```

**Comment by Bencodes** [comment]
@mbland I believe this one has been fixed in HEAD already, at least it was in our project.

**Comment by mbland** [comment]
@Bencodes Indeed it is—confirmed with a `local_path_override()`.

I have it on good authority that a 6.2 release is imminent, but is there a specific commit or PR that has the fix? I can't seem to find anything jumping out in recent commits, PRs, or issues (I searched before filing this, and just now). Not super important, but my OCD would like to know.

**Comment by mbland** [comment]
Ah. I found it (via `git log 6.1..master`): #1122.

**Comment by mbland** [comment]
One more thing... With the fix, the `jvm_import` targets don't have a `srcjar` attribute by default anymore. Setting `fetch_sources = True` restores them.

**Comment by Bencodes** [comment]
https://github.com/bazelbuild/rules_jvm_external/releases/tag/6.2 is officially out with the fix for this duplicate target issue.
