### ISSUE TITLE
Bzlmod: maven.artifact repositories argument is ignored

### ISSUE THREAD

**Issue by plobsing** [bazelbuild/rules_jvm_external#1200]
The `repositories` argument to `maven.artifact` is never consumed. At least, based on my reading of where I'd expect hat to happen: https://github.com/bazelbuild/rules_jvm_external/blob/f3f27fbdfd196074779d351829abd21553490505/private/extensions/maven.bzl#L238C13 as well as observations in practice.

Having a no-op argument, not documented as such, feels like a bit of a gotcha. I believe this argument either should contribute to the set of repositories consulted as part of package resolution, or it should be dropped from the API. Failing that, if there is some reason to keep it around, I believe the docstring for this tag class attr should explain why that is and call out that the argument does nothing in most/all cases.

**Comment by shs96c** [comment]
You're right. I think we should drop it since it T hen makes it clear that the install tag is the only place to set the list of repositories
