### ISSUE TITLE
java_export got javadoc: error - Cannot find doclet class com.sun.tools.doclets.standard.Standard  when build with java8

### ISSUE THREAD

**Issue by nlou9** [bazelbuild/rules_jvm_external#1237]
We are trying to build with java8, .bazelrc looks like 

```
build:java8 --java_language_version=8
build:java8 --java_runtime_version=remotejdk_8
build:java8 --tool_java_language_version=8
build:java8 --tool_java_runtime_version=remotejdk_8
```
java_export target got this error 
```
javadoc: error - Cannot find doclet class com.sun.tools.doclets.standard.Standard
1 error

ERROR: /Users/workspace/BUILD.bazel:11:12: output 'audit/audit-docs.jar' was not created
ERROR: /Users/workspace/BUILD.bazel:11:12: output 'audit/audit-docs-element-list-dir/element-list' was not created
ERROR: /Users/workspace/BUILD.bazel:11:12: Action audit/audit-docs.jar failed: not all outputs were created or valid
```
It seems like `tools.jar` is missing from the classpath. I wonder if it is similar to this [issue](https://github.com/bazelbuild/bazel/issues/21771) in rules_java. Recently rules_java 7.10.0 has a [fix](https://github.com/fmeum/rules_java/commit/89b7b38addba626ecbafc19d1cca56eedf85bdc8) for this.   

found a similar issue in the past:

https://github.com/bazelbuild/rules_jvm_external/issues/438

**Comment by shs96c** [comment]
The tools in `rules_jvm_external` requires Java 11 or above to work properly. While it may be possible to target java 8 with the `java_runtime_version`, you'll need to set `tool_java_language_version` to `11` or higher.
