### ISSUE TITLE
incompatible_new_actions_api

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_jvm_external#148]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/109#1fa8a774-e08e-48d7-b47a-1b2a768c26f2

It looks like this project is not compatible with `--incompatible_new_actions_api`. Can you look at this? You may need to update your dependencies.

Let me know if you need help.

**Comment by jin** [comment]
Which run are you look at? I'm seeing https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/109#40bb570a-df91-483c-b829-d4429c5e01e7 and there's only 

```
Migration is needed for the following flags:
  --incompatible_use_toolchain_resolution_for_java_rules
  --incompatible_windows_style_arg_escaping
```

`bazel test //tests/... --incompatible_new_actions_api` works locally for me.

**Comment by jin** [comment]
Ok, I see it in the robolectric examples https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/109#726a0e38-7fb8-43f2-bbad-d3bfd5fa2309

**Comment by laurentlb** [comment]
The error in the robolectric example looks weird.

However, android_instrumentation_test is also failing (due to protobuf):
`cd examples/android_instrumentation_test && bazel build //src/test:greeter_test --incompatible_new_actions_api --nobuild -k`

**Comment by jin** [comment]
I can repro android_instrumentation_test, and I'll submit a fix.

This is probably the incorrect channel, but I find the experience of upgrading to the newest protobuf as a contributor to the android-test library to be.. not that great. 

android-test is a repo that android_instrumentation_test / android_device rules depend on. By upgrading android-test to the newest protobuf version, we now need to add 

```
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
```

to every Android WORKSPACE that wants to test. Now, as the maintainer of android-test, we need to tell every user to add 

```
http_archive(
    name = "android_test_support",
    sha256 = "c6eb3cae5e37580cf141037cb27815a4e26548757122450ee82008152784ce73",
    strip_prefix = "android-test-%s" % ATS_TAG,
    urls = ["https://github.com/android/android-test/archive/%s.tar.gz" % ATS_TAG],
)

load("@android_test_support//:repo.bzl", "android_test_repositories")
android_test_repositories()
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
```

if we bundle @com_google_protobuf in `android_test_repositories()`. @laurentlb, do you know of a way where we can hide 

```
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
```

from the top level WORKSPACE? AFAIK, we can't call `loads` in `deps.bzl`. It'll be nice if we can keep the `protobuf_deps()` call and the `http_archive` call for protobuf next to each other.

**Comment by laurentlb** [comment]
I agree the user experience is not great (due to the way external deps work and protobuf repository itself).

Can you inline the content of `protobuf_deps` into `android_test_repositories`? I think that's what other rules do.

(see for example https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl)

**Comment by jin** [comment]
Yes. I can inline that. I guess there's no way around but to ask users to add the `protobuf_deps()` call in to their WORKSPACE.

**Comment by laurentlb** [comment]
Yes, that's the pattern.

**Comment by jin** [comment]
Thanks. 

The robolectric tests are failing due to a Skyframe error, so I think we can ignore that. I have seen it once or twice locally, but never got a way to reproduce it..

**Comment by mrk-han** [comment]
> This is probably the incorrect channel, but I find the experience of upgrading to the newest protobuf as a contributor to the android-test library to be.. not that great.

For what it's worth, I appreciate that this channel was used for this discussion! Improving QOL for contributors is always 💯

Thank you!
