### ISSUE TITLE
Consider creating @maven//foo_bar on top of @maven//:foo_bar to share convention across Bazel's external repository rules

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_jvm_external#164]
Context: https://github.com/bazelbuild/rules_jvm_external/pull/160#issuecomment-498977913

**Comment by Globegitter** [comment]
Maybe it is also worth considering a backwards-incompatible way and just exposing `@maven//foo_bar` to not have yet another alias. WDYT?

Also do you think it might be worth adding something to the best practices section the bazel docs about how to fetch external repos and hot to expose them?

**Comment by jin** [comment]
@Globegitter Yeah, it's possible that we can do that but I'm hesitant on changing the API across the ecosystem for a cosmetic reason. 

cc @dslomov @laurentlb for any thoughts about external dep conventions

**Comment by jin** [comment]
Closing this as we'll not be doing this unless there's more demand for a standardized naming style across different package management rulesets.
