### ISSUE TITLE
Exception while implementing Room Database in Android

### ISSUE THREAD

**Issue by akabravo97** [bazelbuild/rules_jvm_external#174]
Hi, I was trying to implement Room Database on Android using Bazel. I tried out this [SO answer](https://stackoverflow.com/questions/56218583/how-to-use-room-database-in-android-with-bazel) by @jin , and I am getting this [Exception](https://pastebin.com/c4rp2g05) while building. Do you guys have any idea why this might be happening?

**Comment by akabravo97** [comment]
Hey guys, Any update on this?

**Comment by jin** [comment]
Can you try adding `com.google.guava:guava:28.1-android` to your list of artifacts in `maven_install`?

**Comment by jin** [comment]
PTAL at the sample project here: https://github.com/jin/BasicRxJavaSample-Bazel
