### ISSUE TITLE
Function pinned_maven_install defined multiple times when there are multiple maven_install declarations 

### ISSUE THREAD

**Issue by krlvi** [bazelbuild/rules_jvm_external#181]
When there multiple `maven_install` defined as per the [docs](https://github.com/bazelbuild/rules_jvm_external#multiple-maven_install-declarations-for-isolated-artifact-version-trees), pinning multiple installs as described in the [docs](https://github.com/bazelbuild/rules_jvm_external#pinning-artifacts) would result in the function `pinned_maven_install` being redefined. 
A workaround is to [alias in the load statement](https://docs.bazel.build/versions/master/build-ref.html#load), for example like so:
```
load("@easyrandom//:defs.bzl", pin_easyrandom = "pinned_maven_install")
pin_easyrandom()
```
It may be worth considering updating the default behaviour in a future release to include the install name in the pin function name.

**Comment by jin** [comment]
This is WAI. The design is for the generated API name to be independent of the repository name, and leave the alias choice to the user. Created https://github.com/bazelbuild/rules_jvm_external/pull/183 to address this in the documentation.

**Comment by krlvi** [comment]
> This is WAI. The design is for the generated API name to be independent of the repository name, and leave the alias choice to the user. Created #183 to address this in the documentation.

Thanks for clarifying this. Would you like me to close this issue or should I leave it for reference in #183 ?

**Comment by jin** [comment]
#183 will close this issue when it's merged.
