### ISSUE TITLE
FR: generate linkable alternative target for neverlink jars

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/rules_jvm_external#185]
I have a project which simultaneously needs `neverlink=True` and `neverlink=False` variants of a dependency, `javax.servlet:javax.servlet-api`. (`neverlink=True` is used by binaries which ship to customers. `neverlink=False` is used by internal tests.)

`jvm_maven_import_external` has a `generated_linkable_rule_name` attribute which automatically generates a secondary `linkable` target for any jars imported with `neverlink=True`. It'd be nice if rules_jvm_external supported an equivalent.

**Comment by jin** [comment]
I prefer to reuse existing constructs to achieve this goal. Can you create a second `maven_install` with the linked/neverlinked variant of `javax.servlet:javax.servlet-api`?

**Comment by beasleyr-vmw** [comment]
Hm, good point. I'll look into creating a second `maven_install` named `maven_stubs` for the neverlink variants.

**Comment by or-shachar** [comment]
We actually have the same issue at Wix and we would love to have the same some built in solution for linkable target. We would prefer not to have multiple `maven_install` calls as it generates two different dependency trees. 

How about generating a linkable target under `@maven//linkable:<name>`? e.g: `@maven//linkable:javax_servlet_javax_servlet_api`

The content of it would be similar to the BUILD file in the root of the generated external repository but the rules would not have `neverlink=True`?

@jin , should we turn it into a feature request? We would love to implement it, if we agree that it's a good solution.

cc: @liucijus @ittaiz @natansil
