### ISSUE TITLE
rules_jvm_external vs java_import_external

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_jvm_external#190]
Hi,

I'm trying to updated a library [here](https://github.com/bazelbuild/rules_webtesting/pull/363) to be compatible with rules_jvm_external. However, there's some confusion about what the current recommended to import external jars and how to reference them. So I've got two questions:

- Which method, `rules_jvm_external` or `java_import_external` (or something else?), is the recommended way to reference external java deps?

- Also, when referencing deps in a library (that other bazel projects will import), what's the best way to reference the deps to be compatible with as many as users as possible (who may be using other jar import methods)?

Thanks,

Doug

**Comment by jin** [comment]
> Which method, rules_jvm_external or java_import_external (or something else?), is the recommended way to reference external java deps?

`java_import_external` is not transitive by default. It is (+ `jvm_maven_import_external`) a drop-in replacement for `maven_jar`. `rules_jvm_external` is a more end-to-end solution for managing a collection of Maven artifacts that needs to be resolved transitively.

> Also, when referencing deps in a library (that other bazel projects will import), what's the best way to reference the deps to be compatible with as many as users as possible (who may be using other jar import methods)?

If you're making a library, I think the best approach is to namespace a `maven_install` repository to your library's name and ask downstream users to add a `maven_install` of that same name with the exact list of artifacts that you can expose through a .bzl load. See https://github.com/buchgr/rules_jmh for an example.

I would advise against going with the `@group_artifact//jar` approach as that's only limited to JAR files, and doesn't encode any information about versions. Downstream users may specify a different version of the artifact, that although resolves to the expected `@group_artifact//jar` label, is of a different version and can cause build failures.

**Comment by jin** [comment]
Addendum: that said, I've opened https://github.com/bazelbuild/rules_jvm_external/pull/192 based on feedback in https://github.com/bazelbuild/rules_webtesting/pull/363 so `rules_jvm_external` is more interoperable with `java_import_external`.

**Comment by Dig-Doug** [comment]
Thanks for the quick fix!

One follow up question about the `maven_install` of the library:

If the user code references external java lib in their code, they'll probably want to specify the dep explicitly in their `maven_install`. If the library, e.g. `rules_webtesting`, also specifies the same library (maybe with a different version) in the bzl `maven_install`, what happens? e.g.

```python
# WORKSPACE
maven_install(
  artifacts = ["lib1:v1"],
)

rules_webtesting_java_deps()
```
```python
# webtesting_macros.bzl
def rules_webtesting_java_deps():
  maven_install(
    artifacts = ["lib1:v2"],
  )
```

Is there a way to combine or input the `rules_webtesting` dependencies into the user's existing `maven_install`? Maybe something like:

```python
# WORKSPACE
load("webtesting_macros.bzl", "WEBTESTING_ARTIFACTS")
maven_install(
  artifacts = ["lib1:v1"],
  external_artifacts = WEBTESTING_ARTIFACTS,
)
```
```python
# webtesting_macros.bzl
WEBTESTING_ARTIFACTS = [
 "lib1:v2",
]
```

**Comment by jin** [comment]
```python
# webtesting_macros.bzl
def rules_webtesting_java_deps():
  maven_install(
    artifacts = ["lib1:v2"],
  )
``` 

should be

```python
# webtesting_macros.bzl
def rules_webtesting_java_deps():
  maven_install(
    name = "rules_webtesting_maven",
    artifacts = ["lib1:v2"],
  )
``` 

and the user's `@maven//:lib1` would not interfere with `@rules_webtesting_maven//:lib1`.

**Comment by Dig-Doug** [comment]
But what happens when the user tries to use them both in a `java_library`?

```python
# My code
java_library(
  name = "my_lib",
  deps = [
    "@maven//:lib1", # Which is using v1
    "@rules_webtesting//:java_interface",
  ],
)
```

```python
# rules_webtesting
java_library(
  name = "java_interface",
  deps = [
    "@rules_webtesting_maven//:lib1", # Which is using v2
  ],
)
```

Won't the two versions conflict?

**Comment by jin** [comment]
Yes, that's a problem with namespaced artifacts that currently doesn't have a solution now, unfortunately. This is not an issue if you refer to the artifacts by `@group_artifact`, since only one version per artifact would be available.

**Comment by Dig-Doug** [comment]
OK, that's fine -- I'm not blocked by it :) I'll file a separate feature request to track it.

Thanks for your help!
