### ISSUE TITLE
Export Artifacts from External Repos 

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_jvm_external#193]
Hi,

Context: #190.

This is a feature request to help support combining external dependencies into a `maven_install`. Here's my use case:

Let's say I am a user and I would like to use another library built by bazel, `rules_webtesting`. `rules_webtesting` exports an interface and uses the `webdriver` library (an external maven artifact). In my code, I also need to use the `webdriver` library and specify it in my maven install:

```python
# WORKSPACE
maven_install(
  artifacts = ["webdriver:v1"],
)
```

```python
# rules_webtesting
java_library(
  name = "java_interface",
  deps = [
    "@maven//:webdriver",
    "@maven//:other_lib",
  ],
)
```

```python
# My code
java_library(
  name = "my_lib",
  deps = [
    "@maven//:webdriver",
    "@rules_webtesting//:java_interface",
  ],
)
```

In the example above, the `rules_webtesting` code needs two dependencies, `webdriver` and `other_lib`. I can't define a separate `maven_install` for the webtesting code because it could conflict with the user's `maven_install`.

```python
# webtesting_macros.bzl
def rules_webtesting_java_deps():
  maven_install(
    name = "rules_webtesting_maven",
    artifacts = [
      # NOTE: This is a different version, so it would conflict with the user's v1
      "webdriver:v2",
      "other_lib",
    ],
  )
```

I'd like a way for a library to export the artifacts they require and for users to input that into their own `maven_install`, maybe something like this:

```python
# WORKSPACE
load("@rules_webtesting//:webtesting_macros.bzl", "WEBTESTING_ARTIFACTS")
maven_install(
  artifacts = ["webdriver:v1"],
  external_artifacts = WEBTESTING_ARTIFACTS,
)
```

```python
# webtesting_macros.bzl
WEBTESTING_ARTIFACTS = [
 "webdriver:v2",
 "other_lib",
]
```

Thanks!

**Comment by jin** [comment]
Why not concat the main maven_install.artifacts with WEBTESTING_ARTIFACTS directly? Coursier will be able to resolve duplicate artifacts in the list and pick the highest version, AFAIUC.

**Comment by Dig-Doug** [comment]
I just tried that, it seems to work and resolve the duplicates :)

Is that the recommended approach? If so, I'll add notes in the README.

**Comment by jin** [comment]
It does seem like the most elegant and simple solution to inherit Maven deps of deps :) feel free to add to the documentation about this.
