### ISSUE TITLE
version range embedded into maven_coordinates tag

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/rules_jvm_external#195]
The generated `jvm_import` rules include a `maven_coordinates` tag per #47. However, if artifact A defines a version range for a dependency on artifact B, then artifact B's tag may contain the range expression instead of the artifact's resolved version.

Example from rules_jvm_external itself:

```console
$ bazel build ...
$ grep -B5 'maven_coordinates.*nimbus-jose-jwt' $(bazel info output_base)/external/regression_testing/BUILD
INFO: Invocation ID: 8d65caca-7e97-460a-baec-6b174439bbff
        jars = ["v1/https/repo1.maven.org/maven2/com/nimbusds/nimbus-jose-jwt/7.4/nimbus-jose-jwt-7.4.jar"],
        deps = [
                ":net_minidev_json_smart",
                ":com_github_stephenc_jcip_jcip_annotations",
        ],
        tags = ["maven_coordinates=com.nimbusds:nimbus-jose-jwt:[4.29,)"],
```
This leads to problem downstream when users of the `maven_coordinates` tag receive a version of `[4.29,)` instead of the expected `7.4`.

**Comment by beasleyr-vmw** [comment]
It looks like this might've been addressed in Coursier with the following commit:

```
commit 360699ff024b226af4dd6a8c68e6ed3430091220
Author: Alexandre Archambault <alexandre.archambault@gmail.com>
Date:   Mon Jul 8 13:51:42 2019 +0200

    Have Resolution.reconciledVersions return actual final versions
```

Since this commit, the JSON report generated when downloading `io.kubernetes:client-java:4.0.0-beta1` contains `"coord": "com.nimbusds:nimbus-jose-jwt:7.4",` instead of `"coord": "com.nimbusds:nimbus-jose-jwt:[4.29,)",`.

**Comment by jin** [comment]
@beasleyr-vmw good to hear. I'm currently waiting for Coursier upstream to release standalone jars for v2.0.0+, so we can integrate with them easily. I'll circle back to this as soon as that's unblocked. https://github.com/coursier/coursier/issues/1265

**Comment by jin** [comment]
Can verify that Coursier v2.0.0-RC3 fixes this: https://github.com/bazelbuild/rules_jvm_external/pull/215/files#diff-021fa6645337cfae38590a1424b640bbL1712
