### ISSUE TITLE
Depending on external repositories that use `maven_install`

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_jvm_external#212]
Discussion lifted from https://github.com/bazelbuild/rules_jvm_external/pull/209

We should figure out the most optimal way to link up repositories that use `rules_jvm_external`/`maven_install`..

The [current guidance in the README](https://github.com/bazelbuild/rules_jvm_external#exporting-and-consuming-artifacts-from-external-repositories) is to load the list of artifacts from the external repo and merge them with your local `maven_install`. This works, and keeps the local workspace clean by using only a single `@maven` repository for all artifacts. It also resolves duplicates and conflicts to comply with the one version policy. However, this doesn't work with `maven_install.json`. 

An idea: If you're using your local `maven_install.json`, use `@//:maven_install.json` or just `//:maven_install.json`. If you're using a external repository's `maven_install.json`, use a function from `rules_jvm_external` that accepts the name assigned to the external repository in the local workspace, and loads some set of variables by convention from the external dependency.

```python
load("@rules_jvm_external//:defs.bzl", "external_maven_install")

http_archive(
    name = "annex",
    urls = [...],
    repo_mapping = {"@maven": "@annex_maven"},
)
# annex_foo workspace depends on `@maven//`, 
# but `@maven` may already be used by the local workspace.

# creates `@annex_maven`
external_maven_install(name = "annex_maven", for_repository = "annex")
```

where `external_maven_install` is a macro that creates a repository rule that loads `@<repository_name>//:maven_install.json` by default and names it `<repository_name>_maven`.

**Comment by borkaehw** [comment]
My current workaround is to prefix `@<repository_name>` in `maven_install`, and I suppose we only need to output the correct format `@<repository_name>//:maven_install.json` after running `bazel run @unpinned_maven//:pin`. It's straightforward and no logic change is needed, like #209.

I personally feel like having a separate macro but doing just a slight different thing, also having a lot of naming attributes, makes it very complex to use.

I appreciate the idea and we can give it a try. I would like to see what it will look like once it's implemented.

**Comment by jin** [comment]
Yeah, you're right. The new macro may be overly complex for this problem.

**Comment by jin** [comment]
Closing this in favor of the simpler fully qualified naming approach for #209.
