### ISSUE TITLE
jvm_rules_external ignores private reposititories in favor of public

### ISSUE THREAD

**Issue by natewest** [bazelbuild/rules_jvm_external#226]
Apologies if this is not a bug per se, but I'm observing jvm_rules_external downloading dependencies from external repositories when they are available in private internal repositories.  I've read through the docs more than once and looked through the source.  Is this expected?  It would be nice if there was an easy way to exclude/block external repositories.

**Comment by jin** [comment]
Are the private repo urls ordered before the external repos in the `repositories` list?

**Comment by natewest** [comment]
I've only specified private repository urls in my maven install rules, yet I see maven artifacts coming from central.maven, repo.maven, etc.  Possibly corsair is somehow fetching transitive dependencies externally in place of using private repositories?

**Comment by jin** [comment]
Coursier should just use the repositories you specified only. What version of rules_jvm_external are you using?

**Comment by natewest** [comment]
Hi Jin,

Thanks for the reply.  Because we have an unreliable external connection we
host our own internal maven repositories.  The install rules specify only
our internal repositories, yet I see failures downloading from external
repositories such as this:

ERROR: An error occurred during the fetch of repository 'maven':
2019-08-20 15:28:29 gobuilds.Compile :    java.io.IOException: Error
downloading [https://jcenter.bintray.com/io/get-coursier/coursier-cli_2.12/1.1.0-M14-4/coursier-cli_2.12-1.1.0-M14-4-standalone.jar,
http://central.maven.org/maven2/io/get-coursier/coursier-cli_2.12/1.1.0-M14-4/coursier-cli_2.12-1.1.0-M14-4-standalone.jar]
to /build/mts/release/bora-14454866/home/mts/.cache/bazel/_bazel_mts/ccfd163fa6862611c604cf04b975aad1/external/maven/coursier:
All mirrors are down: [connect timed out]

This is with rules_jvm_external 2.7.  (commit
65139a89a1562e09df466e88ef2b5790a7c21aad)

**Comment by jin** [comment]
That doesn't look like rules_jvm_external 2.7, because we have changed the rule to download Coursier from GitHub and Bazel Mirror instead of Maven. The Coursier version has also been updated from 1.1.0 to 2.0.0. Could you please confirm?

**Comment by natewest** [comment]
Jin, please see the commit I provide in my previous comment.  That corresponds to rules_jvm_external 2.7, correct?

**Comment by jin** [comment]
Hmm, yes, that's right. It's odd that it's downloading from Maven still, when the commit has switched it download from GitHub and the Bazel mirror instead. I'll try to reproduce this soon.

**Comment by natewest** [comment]
Jin, I'm going to close this for now.  I think the problem was due to not pinning.
