### ISSUE TITLE
Don't print unnecessary pin.sh instruction

### ISSUE THREAD

**Issue by borkaehw** [bazelbuild/rules_jvm_external#232]
Every time after running `bazel run @unpinned_mavan//:pin`, we see instructions like
```
Successfully pinned resolved artifacts for @maven ...
...
```
It is useful the first time we run `bazel run @mavan//:pin`, but unnecessary when we already have
```
maven_install(
    artifacts = # ...,
    repositories = # ...,
    maven_install_json = "//:maven_install.json",
)

load("@maven//:defs.bzl", "pinned_maven_install")
pinned_maven_install()
```
in the `WORKSPACE` and instruction of running `bazel run @unpinned_mvn//:pin` can be skipped if that instruction is generated by running `bazel run @unpinned_mvn//:pin`.

I would suggest if users are already using pinned json, the message could be as simple as 
```
Successfully pinned resolved artifacts for @maven, maven_install.json is now up-to-date.

**Comment by jin** [comment]
That's a good idea. Happy to take a PR for this!

**Comment by borkaehw** [comment]
Thanks for your support. I don't have bandwidth this week, I will draft a PR when I get a chance. Everyone is welcome to address this issue.
