### ISSUE TITLE
FR: override_targets attr shouldn't override artifacts attr

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/rules_jvm_external#235]
Imagine I have a `maven_install.bzl` file for a single product but with a lot of projects. The projects should usually stick to common artifact versions, but some projects may choose to use their own versions. Common versions can be enforced using the `override_targets` attribute, but this has a slightly surprising side effect of overriding the artifacts specified in the `artifacts` attribute.

I can work around this by wrapping `maven_install` and filtering `artifacts` from `override_targets`, but I wonder if this or similar logic should be baked directly into rules_jvm_external.

```console
$ cat deps.bzl
load("@rules_jvm_external//:defs.bzl", "maven_install")

_COMMON_DEPS = [
    "io.opentracing:opentracing-api:0.31.0",
]

def _to_bazel(term):
    return term.replace("-", "_").replace(".", "_")

def _to_override(ns, gav):
    group, artifact = gav.split(":")[0:2]
    lhs = group + ":" + artifact
    rhs = "@{}//:{}_{}".format(ns, _to_bazel(group), _to_bazel(artifact))
    return lhs, rhs

def deps():
    maven_install(
        name = "common_deps",
        artifacts = _COMMON_DEPS,
        repositories = ["https://repo1.maven.org/maven2"],
    )

    maven_install(
        name = "project_deps",
        artifacts = ["io.opentracing:opentracing-api:0.32.0"],
        override_targets = {
            x: y
            for (x, y) in [_to_override("common_deps", z) for z in _COMMON_DEPS]
        },
        repositories = ["https://repo1.maven.org/maven2"],
    )
$ cat BUILD
java_library(
    name = "common_java_test_deps",
    exports = [
        "@common_deps//:io_opentracing_opentracing_api",
    ],
)

java_library(
    name = "project_java_test_deps",
    exports = [
        "@project_deps//:io_opentracing_opentracing_api",
    ],
)
$ bazel cquery --noimplicit_deps 'deps(:project_java_test_deps)' 2>/dev/null | grep tracing 
@common_deps//:io_opentracing_opentracing_api (b67bdc290fb31b127eacf7a9889db436)
@common_deps//:io_opentracing_opentracing_api (b67bdc290fb31b127eacf7a9889db436)
@common_deps//:v1/https/repo1.maven.org/maven2/io/opentracing/opentracing-api/0.31.0/opentracing-api-0.31.0.jar (null)
```

**Comment by jin** [comment]
> Common versions can be enforced using the override_targets attribute, but this has a slightly surprising side effect of overriding the artifacts specified in the artifacts attribute.

This is intended behavior. The purpose of `override_targets` is to modify artifacts in `@maven`, or more precisely, generated targets in `@maven`'s BUILD file to point to a locally defined target instead. 

What do you think we can do to make this clearer in the doc?

**Comment by beasleyr-vmw** [comment]
> > Common versions can be enforced using the override_targets attribute, but this has a slightly surprising side effect of overriding the artifacts specified in the artifacts attribute.
> 
> This is intended behavior. The purpose of `override_targets` is to modify artifacts in `@maven`, or more precisely, generated targets in `@maven`'s BUILD file to point to a locally defined target instead.
> 
> What do you think we can do to make this clearer in the doc?

Ahh, gotcha. Rereading the current docs, I have no idea how I came to a different interpretation. I'll close this, then. Thanks!
