### ISSUE TITLE
Best practise to add Pubsub

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_jvm_external#240]
Trying to use Pubsub, I added the following to my `WORKSPACE`:
```
maven_install(
    artifacts = [
        "com.google.cloud:google-cloud-pubsub:1.90.0",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
```
(and `com.google.cloud:google-cloud-pubsub` to my `deps`).

Naively I thought I could then use Pubsub just fine. I get the error message though:
```
src/java/my/pubsub/Consume.java:12: error: [strict] Using type com.google.pubsub.v1.PubsubMessage from an indirect dependency (TOOL_INFO: "external/maven/v1/https/jcenter.bintray.com/com/google/api/grpc/proto-google-cloud-pubsub-v1/1.72.0/proto-google-cloud-pubsub-v1-1.72.0.jar").
	public void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
```
Referencing grpc seems "wrong" though.
So what is the semantic best practise to get this reference working in Bazel?

**Comment by jin** [comment]
You need to add `@maven//:com_google_api_grpc_proto_google_cloud_pubsub_v1` to your deps, because transitive dependencies aren't re-exported automatically by the top level artifact.  

This is https://github.com/bazelbuild/rules_jvm_external/issues/147
