### ISSUE TITLE
[FR] - Create Pinned json in a different directory?

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/rules_jvm_external#251]
Would it be possible for `@repo//:pin` and `@unpinned//:pin` commands to generate the pinned json file under a different directory?

I.e. given:

```
WORKSPACE
bazel_extensions/
  pinned_dependencies/
    repo_install.json
```

Could we write to the same place we read the file from? I.e. `maven_install_json: "//:bazel_extensions/pinned_dependencies/repo_install.json" will read from that file, but when running `@unpinned_repo//:pin` won't update that file and instead creates a new one in the top dir.

**Comment by jin** [comment]
Yes. The initial location should still be `<root>/maven_install.json`, but subsequent calls to `@unpinned_maven//:pin` should infer the new location from the attribute and override the existing json.

Happy to take a PR for this.

**Comment by jin** [comment]
See #257
