### ISSUE TITLE
http proxy urls with username and password are not parsed correctly

### ISSUE THREAD

**Issue by cheister** [bazelbuild/rules_jvm_external#261]
an http_proxy or https_proxy with a username and password do not parse the username and password and do not set the `http.proxyPassword` or `http.proxyUser` java vars.

e.g. https://user:pass@proxy.com:443 will set `http.proxyHost` to `user` and `http.proxyPort` to `pass@proxy.com:443`

**Comment by jin** [comment]
Fixed by #262
