### ISSUE TITLE
Method to use tests jars for unit and integration tests

### ISSUE THREAD

**Issue by georgefintechstudioscom** [bazelbuild/rules_jvm_external#267]
We are using  Bazel in development of a Flink system.  We are creating user defined mapping functions that make use of metrics classes, such as Counter.  We want to create unit tests for these functions, and the Flink documentation refers to various test harness classes such as OneInputStreamOperatorTestHarness. Some research shows that this class is in flink-streaming-java_2.11-1.9.0-tests.jar (and other versions, but the emphasis is on *-tests.jar).  The usual method of using maven_install() for 
        maven.artifact(
            group = "org.apache.flink",
            artifact = "flink-streaming-java_2.11",
            version = "1.9.0",
        ),
only leaves access to the main jar which does not have the test harness classes.  As a result, the compiler cannot find these classes, and building fails.

We played around a bit, and found that adding this to WORKSPACE:

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")
http_jar(
      name = "flinkStreamingTest",
      url = "https://repo1.maven.org/maven2/org/apache/flink/flink-streaming-java_2.11/1.9.0/flink-streaming-java_2.11-1.9.0-tests.jar",
      sha256 = "da6e1bf467c2f5f237729e76f3d0999f3e96d6e115a0eddeb3cf9a6c50046e6b",
) 

...and then making a reference to "@flinkStreamingTest//jar" in the BUILD file added the necessary external library and reference, and we are now able to build and test.

But is this a recommended approach to making use of tests jars for Flink using Bazel, or is there a better way?  If there is not, would it make sense to add "scope" to the maven.artifact object to indicate which jar to use in a dependency?

**Comment by austince** [comment]
Perhaps adding the `tests` classifier would solve this? And then adding a `fetch_tests` option to `maven_install`, similar to `fetch_sources`? 

https://github.com/bazelbuild/rules_jvm_external/blob/6add0ba95304715013060b5d160541e83775eb9f/coursier.bzl#L54-L55

**Comment by georgefintechstudioscom** [comment]
Along those lines, austince, I have trie the following:

maven_install(
    name = "testJars",
    artifacts = [
        maven.artifact(
            group = "org.apache.flink",
            artifact = "flink-streaming-java_2.11",
            packaging = "jar",
            classifier = "tests",
            version = "1.9.0",
        ),
        maven.artifact(
            group = "org.apache.flink",
            artifact = "flink-runtime_2.11",
            packaging = "jar",
            classifier = "tests",
            version = "1.9.0",
        ),
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
(I did not try this originally because the IntelliJ IDE was directing me to a function named "artifact" that was not what "maven.artifact" actually refers to...another issue.)
This method works beautifully for "flink-runtime", but fails with 

no such target '@testJars//:org_apache_flink_flink_streaming_java_2_11': target 'org_apache_flink_flink_streaming_java_2_11' not declared in package ''

This problem seems to be specific to flink-streaming-java, which I noticed has a Maven "scope" of "provided" instead of "tests", but I don't know if that matters.

**Comment by georgefintechstudioscom** [comment]
Correction.  This new method simply displays one error at a time, and flink-runtime does not work once flink-streaming-java is removed.  Nevermind.

**Comment by georgefintechstudioscom** [comment]
I finally found that using the maven_install() method specifying packaging and classifier works, as long as you also refer to the packages with the classifier appended to the name (but not the version), like this:

        "@testJars//:org_apache_flink_flink_runtime_2_11_tests",
        "@testJars//:org_apache_flink_flink_streaming_java_2_11_tests",
