### ISSUE TITLE
Updating maven_install.json location does not work

### ISSUE THREAD

**Issue by cfredhart** [bazelbuild/rules_jvm_external#276]
I cannot get custom locations of `maven_install.json` to work. I want to put the file in a  subdirectory of my workspace. I generated a `maven_install.json` file in the workspace directory and added the requisite items to the `WORKSPACE` file and got pinning to work. I then changed the `maven_install_json` path to point to the subdirectory, `bazel` as below.
```
maven_install_json = "//bazel:maven_install.json"
```
Running 
```
bazel run @unpinned_maven//:pin
```
regenerated the `maven_install.json` file in the workspace directory and not the subdirectory. Running 
```
bazel run @maven//:pin
```
does not seem possible with the `maven_install_json` attribute set so how does one change the location of the `maven_install.json`?

**Comment by jin** [comment]
This feature hasn't been released yet, but the README has been updated. Let me make a new release.

**Comment by jin** [comment]
Please use version 2.9: https://github.com/bazelbuild/rules_jvm_external/releases/tag/2.9
