### ISSUE TITLE
Gradle migration guide

### ISSUE THREAD

**Issue by gioragutt** [bazelbuild/rules_jvm_external#279]
I’m think about the possibility of using Bazel instead of gradle, and I don’t see any reasonable migration guide available anywhere.

We currently work in a multi-repo setup, have an on-premise artifactory (we work in an isolated network), and use gradle for the build.

At this stage, is this possible to migrate from gradle to bazel?

Just to be thorough, I’m talking about backend java, not android.

**Comment by jin** [comment]
> We currently work in a multi-repo setup, 

Yes - Bazel supports sewing repositories together into a "virtual monorepo" via `http_archive`/`git_repository` rules.

> have an on-premise artifactory (we work in an isolated network), and use gradle for the build.

rules_jvm_external supports custom repositories, so yes. I've personally reviewed a couple of large Gradle -> Bazel migrations, and it's possible.

Feel free to continue chatting on Bazel Slack's #java and #maven channels: https://slack.bazel.build

**Comment by borkaehw** [comment]
There are a [bazel-discuss](https://groups.google.com/forum/#!forum/bazel-discuss) mailing list and a [bazel-dev](https://groups.google.com/forum/#!forum/bazel-dev) mailing list. These could be good places to get advice.

I have used Bazel for Scala for over a year. It has been a great experience. I encourage you to give a it shot. :smile: 

FYI, Bazel just hit [1.0 milestone](https://opensource.googleblog.com/2019/10/bazel-reaches-10-milestone.html). It's the first general availability release. I believe it's a good time to migrate.

**Comment by gioragutt** [comment]
The thing is that we:
1. Work in an offline environment, and bringing over software to our environment is painful, and sometimes the process itself is unavailable 🤷🏻‍♂️
2. The migration needs to be as simple as possible, as we have a ton of juniors, not many seniors, and this has to be something that should be easily migrated to.

I hope that one day we'll move to bazel (considering we have a C++/Java/Angular stack, which fits Bazel perfectly), but this has to be a smooth process to even be given time to work on it.

**Comment by jin** [comment]
Any Bazel project can be bootstrapped entirely using the `--distdir` flag: https://docs.bazel.build/versions/master/guide.html#distdir

In the case of downloading Coursier from the internet, you can check in the Coursier binary into a distribution directory and point Bazel to it. If the file's basename and checksum match, Bazel will skip the network call.
