### ISSUE TITLE
Migration tool hangs

### ISSUE THREAD

**Issue by georgewfraser** [bazelbuild/rules_jvm_external#287]
When I run `bazel run @rules_jvm_external//migration:maven_jar` nothing seems to be happening. I can't tell if it's broken or if it's just taking a long time. 

Does this command give any sort of feedback about what it's doing? Should I expect it to take a long time in a large repo?

**Comment by jin** [comment]
It'll take a long time in a large repository, especially with the BUILD file changes with buildozer. We can definitely add some feedback to the progress.

**Comment by georgewfraser** [comment]
FYI, I ended up looking at the source code for the migration and writing my own buildozer migrations manually, and buildozer was MUCH faster when I executed all the migrations in a single invocation of buildozer.

**Comment by jin** [comment]
Closing this as maven_jar has been gone for a while now, and I don't think there's a need to work on this unless folks are severely blocked on it.
