### ISSUE TITLE
Most entries of stamped jar manifests are deleted when Target-Label is added

### ISSUE THREAD

**Issue by cheister** [bazelbuild/rules_jvm_external#292]
In https://github.com/bazelbuild/rules_jvm_external/pull/285 the manifest files of jars are replaced to add the `Target-Label` entry.  This removes useful manifest entries such as `Main-Class` and `Multi-Release` which breaks the usage of some jars.

`Target-Label` should be added to the existing `META-INF/MANIFEST.MF` file instead of replacing the existing entries.

**Comment by jin** [comment]
Oof, I missed this. On it.

**Comment by gergelyfabian** [comment]
Any progress on this issue? This is a blocking issue (at least for my use case) that makes upgrading from 2.9 to latest master impossible.

**Comment by gergelyfabian** [comment]
My take for this is to disable the problematic functionality: https://github.com/gergelyfabian/rules_jvm_external/tree/remove_jar_stamping.

As for a real fix, unfortunately I do not know how to retrieve the manifest entries of the input jar for this role (jvm_import), but I understand that those manifest entries should be retrieved and then provided as additional options after 'args.add("--deploy_manifest_lines")'.

**Comment by jin** [comment]
@gergelyfabian, @cheister and I are discussing ways to retain the original manifest entries in this PR: https://github.com/bazelbuild/rules_jvm_external/pull/293

**Comment by jin** [comment]
Fixed by #293
