### ISSUE TITLE
Bazel using JAR Coursier downloads when jar version has extra metadata

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/rules_jvm_external#302]
## Problems
It appears whatever mechanism is being used to copy the jar Coursier downloads for Bazel to use as a cache is not working when the jar version has extra metadata. For example: `org.postgresql:postgresql:9.4-1201-jdbc41`. It appears the cache misses and then falls back to using `http_file` which tries to fetch the JAR and fails because it does not have the auth credentials (making me think it was this issue: https://github.com/bazelbuild/rules_jvm_external/issues/80)

## Stacktrace
```
ERROR: /private/var/tmp/_bazel_kaoru/<sha>/external/private_repo/BUILD:245:1: @private_repo//:org_postgresql_postgresql_9_4_1201_jdbc41_extension depends on @org_postgresql_postgresql_9_4_1201_jdbc41//file:file in repository @org_postgresql_postgresql_9_4_1201_jdbc41 which failed to fetch. no such package '@org_postgresql_postgresql_9_4_1201_jdbc41//file': java.io.IOException: Error downloading [https://internal-nexus-repo.example.com/content/groups/public/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar, https://internal-nexus-repo.example.com/content/repositories/releases/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar, https://internal-nexus-repo.example.com/content/repositories/snapshots/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar] to /private/var/tmp/_bazel_kaoru/<sha>/external/org_postgresql_postgresql_9_4_1201_jdbc41/file/downloaded: GET returned 401 Unauthorized
```

## Symptoms
This only occurs when 
- trying to pull down jars _only_ available in privates repos
- the jar has extra metadata, i.e. `org.postgresql:postgresql:9.4-1201-jdbc41`
- using Coursiers dotfile authentication

## Versions
Platform: Mac OS X 10.14.6
Bazel: 1.2.1

**Comment by KaoruDev** [comment]
or maybe this is same as https://github.com/bazelbuild/rules_jvm_external/issues/186 ?

**Comment by KaoruDev** [comment]
Oh huh, I actually don't understand, but let me see if I can explain it, please correct me.

It seems to me that `rules_jvm_external` uses Coursier to fetch jars and create the `.json` manifest file. But when a user actually ends up using it, it re-fetches the jar via `http_files` is that correct?

**Comment by jin** [comment]
> It seems to me that rules_jvm_external uses Coursier to fetch jars and create the .json manifest file. But when a user actually ends up using it, it re-fetches the jar via http_files is that correct?

@KaoruDev yes if you're using artifact pinning, Coursier is only used to create the json manifest. It delegates the actual downloading to a Bazel repository rule's `ctx.download` to make use of Bazel's repository cache.

**Comment by KaoruDev** [comment]
kk gonna close this in favor of #186
