### ISSUE TITLE
mirror.bazel.build/coursier_cli/coursier_cli_v2_0_0_RC3_4.jar does not match expected checksum

### ISSUE THREAD

**Issue by timonvo** [bazelbuild/rules_jvm_external#318]
https://github.com/bazelbuild/rules_jvm_external/commit/fae429a0c3a5c0da4d4380eeaf347f5331083a5f#diff-1c461cf49716b4c0519ab0cc8ea8040f bumped rules_jvm_external's coursier version to  2.0.0-RC3-4, and updated the checksum accordingly to 8f35f92fb8e021f96b3aa8145c66c3b2e29295baabb28ff50569e613438afcbd. This checksum does seem to match the https://github.com/coursier/coursier/releases/download/v2.0.0-RC3-4/coursier.jar correctly.

However, it looks like the corresponding mirrored file at https://mirror.bazel.build/coursier_cli/coursier_cli_v2_0_0_RC3_4.jar does not actually match that checksum. Instead it seems to match the old checksum 17f4ff053d0d1dca588afdcc94ca952f7ed85bb03675cd77ec05b7352a832b86 for the Coursier 2.0.0-RC3 release.

Is it possible that coursier_cli_v2_0_0_RC3.jar was accidentally uploaded as coursier_cli_v2_0_0_RC3_4.jar to mirror.bazel.build?

I noticed this after running a build, which tried to first download from Github but failed (most likely transiently), and the fell back to the mirror.bazel.build mirror and subsequently failed due to hash mismatch:
$ bazel build //my/target
ERROR: An error occurred during the fetch of repository 'maven':
   java.io.IOException: Error downloading https://github.com/coursier/coursier/releases/download/v2.0.0-RC3-4/coursier.jar, https://mirror.bazel.build/coursier_cli/coursier_cli_v2_0_0_RC3_4.jar] to <snip>/.cache/bazel/<snip>/external/maven/coursier: Checksum was 17f4ff053d0d1dca588afdcc94ca952f7ed85bb03675cd77ec05b7352a832b86 but wanted 8f35f92fb8e021f96b3aa8145c66c3b2e29295baabb28ff50569e613438afcbd

**Comment by jin** [comment]
Thanks for the report! I've fixed this. 

```
$ curl https://mirror.bazel.build/coursier_cli/coursier_cli_v2_0_0_RC3_4.jar  | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.2M  100 28.2M    0     0  9675k      0  0:00:02  0:00:02 --:--:-- 9675k
8f35f92fb8e021f96b3aa8145c66c3b2e29295baabb28ff50569e613438afcbd  -
```
