### ISSUE TITLE
Generated files use native java_import

### ISSUE THREAD

**Issue by arturdryomov** [bazelbuild/rules_jvm_external#329]
Honestly saying, I’m not sure it is a `rules_jvm_external` issue but it seems this way.

Running Bazelisk with the `--strict` flag might show this error.

```
INFO: Build options --incompatible_disable_native_android_rules, --incompatible_enable_cc_toolchain_resolution, --incompatible_load_cc_rules_from_bzl, and 5 more have changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_user/d6e85247c27f29d694672a28ac6d18f5/external/io_bazel_rules_kotlin_org_apache_ant_ant/jar/BUILD:3:1: in java_import rule @io_bazel_rules_kotlin_org_apache_ant_ant//jar:jar: The native Java rules are deprecated. Please load java_import from the rules_java repository. See http://github.com/bazelbuild/rules_java and https://github.com/bazelbuild/bazel/issues/8741. You can temporarily bypass this error by setting --incompatible_load_java_rules_from_bzl=false.
ERROR: Analysis of target '//tests/integration:detekt_html_report' failed; build aborted: Analysis of target '@io_bazel_rules_kotlin_org_apache_ant_ant//jar:jar' failed; build aborted
INFO: Elapsed time: 0.638s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 383 targets configured)
```

The generated `BUILD` file looks like this:

```python
package(default_visibility = ['//visibility:public'])
java_import(
    name = 'jar',
    tags = ['maven_coordinates=org.apache.ant:ant:1.9.9'],
    jars = ['io_bazel_rules_kotlin_org_apache_ant_ant.jar'],
    srcjar = ":io_bazel_rules_kotlin_org_apache_ant_ant-sources.jar",
)
filegroup(
    name = 'file',
    srcs = [
        'io_bazel_rules_kotlin_org_apache_ant_ant.jar',
        'io_bazel_rules_kotlin_org_apache_ant_ant-sources.jar'
    ],
    visibility = ['//visibility:public']
)
```
So the error seems to be legit since there is no `load` declaration for `java_import`.

I think [the `_generate_imports` function](https://github.com/bazelbuild/rules_jvm_external/blob/a4545376518673fa02688faab925cb534d84da8a/private/dependency_tree_parser.bzl#L47) is responsible for the above `BUILD` file generation.

**Comment by jin** [comment]
We haven't been using java_import for a while. What version of the rules is this?

**Comment by arturdryomov** [comment]
Seems to be [3.0](https://github.com/buildfoundation/bazel_rules_detekt/blob/master/WORKSPACE#L42). The function I’ve mentioned above actually contains the `java_import` declaration.

**Comment by jin** [comment]
`io_bazel_rules_kotlin_org_apache_ant_ant` is probably pulled in by rules_kotlin, not rules_jvm_external. rules_jvm_external doesn't use java_import anywhere.

**Comment by jin** [comment]
https://github.com/bazelbuild/rules_kotlin/blob/8ca948548159f288450516a09248dcfb9e957804/third_party/jvm/workspace.bzl#L114

**Comment by arturdryomov** [comment]
Ah, yes, it is `jvm_import`! My brain refused to see the difference, sorry. Clothing this one, will open for `rules_kotlin`. Thanks!
