### ISSUE TITLE
3.1 seems to have a limit to the number of artifacts it will hash

### ISSUE THREAD

**Issue by justhecuke** [bazelbuild/rules_jvm_external#357]
> ERROR: An error occurred during the fetch of repository 'unpinned_maven':
>    Error while obtaining the sha256 checksums: java.io.IOException: Cannot run program "/var/tmp/_bazel_jwei/install/4f12cbbb3a294bfa314e578758559d54/process-wrapper" (in directory "/private/var/tmp/_bazel_jwei/3e5cafa66bb3fb562cc9f4a87160325d/external/unpinned_maven"): error=7, Argument list too long

I've verified that this does not happen in 3.0 but does happen in 3.1. I assume this is due to https://github.com/bazelbuild/rules_jvm_external/pull/314 but I haven't tried a local test to see if this is actually the case.

**Comment by jin** [comment]
Looks like we need to batch this up.

cc @joprice

**Comment by joprice** [comment]
That makes sense. I hadn't hit that for the number of deps I'm currently using. @justhecuke Thanks for the quick fix!

**Comment by justhecuke** [comment]
@joprice Thanks for making the optimization in the first place. Our maven loads take about 20-30% of the time now.
