### ISSUE TITLE
Hasher invocation fails in a project with many dependencies

### ISSUE THREAD

**Issue by rivashin** [bazelbuild/rules_jvm_external#363]
OS: Windows 10
Bazel version: 2.0.0
rules_jvm_external version: 3.1

Bazel fails on our average-sized project (with ~100 dependencies declared in maven_install) because the generated command line for the hasher is too long:
`CreateProcessWithExplicitHandles("java" -noverify ...): command is longer than CreateProcessW's limit (32767 characters)`

Writing the list of input filenames into a temp file and passing the name of that file as the only argument seems to be a better way of doing this.

Caused by: https://github.com/bazelbuild/rules_jvm_external/pull/314

**Comment by artem-zinnatullin** [comment]
This issue has already been fixed by #360 :)

**Comment by rivashin** [comment]
Nice, thanks for pointing this out!
Will try again next week.

**Comment by jin** [comment]
Fixed by #360, will make a release soon.

**Comment by herry-c** [comment]
I had the same problem.
OS: Windows 10
Bazel version: 4.0.0
rules_jvm_external version: 4.0

 Error while fetching artifact with coursier: java.io.IOException: ERROR: src/main/native/windows/process.cc(165): CreateProcessWithExplicitHandles("D:\tools\javajdk\bin\java" -noverify -jar fetch org.apache.zookeeper:zookeeper-jute:3.6.0 org.apache.zookeeper:zookeeper-jute:3.6.2 org.apache.zookeeper:zookeeper:3.6.2-h0.gdd.sop.r18 io.grpc:grpc-api:1.36.1 io.grpc:grpc-context:1.36.1 io.grpc:grpc-core:1.36.1 io.grpc:grpc-grpclb:1.36.1 io.grpc:grpc-netty:1.36.1 io.grpc:grpc-protobuf-lite:1.36.1 io.grpc:grpc-protobuf:1.36.1 io.grpc:grpc-stub:1.36.1 org.quartz-scheduler.in(...)): command is longer than CreateProcessW's limit (32767 characters)
