### ISSUE TITLE
Enable parallel threads in Coursier on Windows

### ISSUE THREAD

**Issue by rivashin** [bazelbuild/rules_jvm_external#365]
Currently rules_jvm_external forces Courier to use only one thread on Windows. Apparently this used to cause Coursier to crash.

https://github.com/coursier/coursier/issues/1223

Is this still an issue? Can anybody reproduce it?
I've changed this setting to 6 and it seems to work fine, I haven't seen any crashes on Windows 10 with Bazel 2.0

**Comment by jin** [comment]
if you no longer see the crash on Windows with more threads, please feel free to open the PR to remove it. We'll be able to catch breakages on CI too;
