### ISSUE TITLE
If you resolve more than one bom or pom file it will be discarded in the pinned json file because the filepath is null

### ISSUE THREAD

**Issue by cheister** [bazelbuild/rules_jvm_external#371]
When a pom artifact or bom artifact is resolved by coursier it returns a null filepath.  The deduplication used the filepath to remove duplicate dependencies.  Since multiple pom artifacts all have null filepath only the first one will be add to the dependencies and all other will be removed by the deduplication.

Coursier doesn't support boms yet https://github.com/bazelbuild/rules_jvm_external/issues/229 but if they are brought in by other dependencies then dependency resolution shouldn't fail.

**Comment by jin** [comment]
Fixed by #372, I believe.
