### ISSUE TITLE
org.apache.commons:commons-io:1.3.2 seems to be resolved incorrectly

### ISSUE THREAD

**Issue by borkaehw** [bazelbuild/rules_jvm_external#382]
When I use
```
maven_install(
    artifacts = [
        "com.browserstack:browserstack-local-java:1.0.3",
    ],
    repositories = [
        "https://repo.maven.apache.org/maven2",
    ],
    maven_install_json = "//:maven_install.json",
    ...
)
```
The pinned file is resolved to
```
"coord": "com.browserstack:browserstack-local-java:1.0.3",
"dependencies": [
    "commons-io:commons-io:1.3.2",
    "org.json:json:20160212",
    "org.apache.commons:commons-io:1.3.2"
],
```
`org.apache.commons:commons-io:1.3.2` is required in deps but it's not listed in the json. So I got
```
in deps attribute of jvm_import rule @maven//:com_browserstack_browserstack_local_java: rule '@maven//:org_apache_commons_commons_io' does not exist
```
Enforcing the artifacts doesn't work.
```
artifacts = [
    "com.browserstack:browserstack-local-java:1.0.3",
    "org.apache.commons:commons-io:1.3.2",
],
```
The resolved json stays the same. Currently there is no workaround.

Interestingly, if I just resolve
```
artifacts = [
    "org.apache.commons:commons-io:1.3.2",
],
```
The output is still incorrect, I only got
```
"coord": "commons-io:commons-io:1.3.2",
```

Does anyone have insight what might be the issue? Thanks.

**Comment by borkaehw** [comment]
@jin Do you get a chance to take a look at it? It would be good to find a workaround if we don't have a immediate solution.

**Comment by jin** [comment]
This is https://github.com/bazelbuild/rules_jvm_external/issues/250 right?

**Comment by borkaehw** [comment]
Ah you are right, sorry I didn't realize that in the issue title.
