### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by mandrean** [bazelbuild/rules_jvm_external#383]
Sometimes you end up with these situations:

![image](https://user-images.githubusercontent.com/4631744/74865788-fff62800-5351-11ea-91af-90aefc1a5294.png)

Some kind of debug mode with more verbose logging would be really helpful!

**Comment by jin** [comment]
We can use an environment variable `RULES_JVM_EXTERNAL_DEBUG` to toggle additional debug printouts for this.
