### ISSUE TITLE
fetch_sources fails with command line too large with 500+ artifacts

### ISSUE THREAD

**Issue by btbuxton** [bazelbuild/rules_jvm_external#387]
Using maven_install 3.1 on bazel 1.0.0 on Mac.

Seeing an issue when fetch_sources=True maven_install fails with command line too large. The maven_install rule has over 500+ artifacts. No resources are downloaded. Works fine with fetch_sources=False.

Need to have this working for development. This is blocking Bazel 2.0 upgrade.

**Comment by jin** [comment]
This should be https://github.com/bazelbuild/rules_jvm_external/issues/357.

Please try 3.2 and let us know if it works.

**Comment by jin** [comment]
Closing this as the bug was fixed by @justhecuke, and fix released in 3.2.
