### ISSUE TITLE
pinned JSON file sort is unstable

### ISSUE THREAD

**Issue by kevingessner** [bazelbuild/rules_jvm_external#395]
The `pin.sh` script to generate the pinned install JSON uses `python -m json.tool` to format the JSON.  Unfortunately, `json.tool` changed its default behavior between python2 and python3: objects were sorted by key in py2, but not in py3.  This causes a lot of churn in the file, depending on what `python` is in the PATH of the last person to generate the file.  It would be better to use a consistent formatter, e.g.:

1. explicitly use `python2 -m json.tool` or `python3 -m json.tool`
2. use `python`'s json lib directly to format the JSON with code that is compatible with both 2 and 3
3. use something like `jq` instead (brought in via the workspace)
4. make the JSON formatter configurable in the repository rule

I can put together a PR for one of the above or a different idea.  Do you have a preference for fixing this?

**Comment by jin** [comment]
Thanks for the heads up. I prefer option 3: one that works with minimal dependency overhead and configuration by the end user, and we can also drop the dependency on system python for pinning.
