### ISSUE TITLE
Multimodule project dependencies

### ISSUE THREAD

**Issue by tzimisce012** [bazelbuild/rules_jvm_external#415]
Hi guys, I am having the following issues and I don't know if I am doing something wrong or this is the expected behaviour of `rules_jvm_external`.

I have a monorepo with multiple projects in `Bazel`. I have a project `A` that depends on a project `B`. This project `B` has a maven dependency, that I want to use in project `A`. Turns out, that I have to write down in the `BUILD` file of project `A` that maven dependency too instead of grabbing it from project `B`. 

Is this the expected behaviour?

Bazel version: 3.1.0

**Comment by jin** [comment]
Please read this section on managing maven_install across multiple repositories: https://github.com/bazelbuild/rules_jvm_external#exporting-and-consuming-artifacts-from-external-repositories

The general problem is that Bazel does not have recursive workspace support. What you have specified in B's WORKSPACE file is not directly available in A's WORKSPACE. A needs to explicitly specify everything it needs in its own WORKSPACE, or load information from files in B's .bzl files.

**Comment by plaird** [comment]
If your dependency is within the same WORKSPACE, just different BUILD files, check out the _exports_ attribute on java_library:

https://docs.bazel.build/versions/master/be/java.html#java_library.exports
