### ISSUE TITLE
Cannot download jar

### ISSUE THREAD

**Issue by CQBB** [bazelbuild/rules_jvm_external#441]
Maybe not an issue, but i followed all the steps, i was not able to download the jar into my `External Libraries`. The build was successful. What i tried
1. `bazel run @maven//:pin`
2. pecify maven_install_json in maven_install and load pinned_maven_install from @maven//:defs.bzl
3. `bazel fetch @maven//... `
Which is the command to download the jar?

My WORKSPACE:

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "3.3"
RULES_JVM_EXTERNAL_SHA = "d85951a92c0908c80bd8551002d66cb23c3434409c814179c0ff026b53544dab"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "junit:junit:4.12",
        "com.google.guava:guava:28.0-jre",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    fetch_sources = True,
    maven_install_json = "//:maven_install.json",
)

load("@maven//:defs.bzl", "pinned_maven_install")
pinned_maven_install()

Thanks a lot.

**Comment by shs96c** [comment]
`External Libraries`? I assume you're talking about the IntelliJ plugin? If so, add a target that depends on one of the artifacts that you've downloaded, and then refresh the project (`Bazel -> Sync -> Sync project with BUILD files`) and it _should_ show up. My understanding is that the plugin will only add things that appear in the transitive dependencies of the targets it detects.

If I've misunderstood, please let me know, as I'm not quite sure what else you mean.

I've I've understood correctly and things work, please feel free to close the issue. If the issue persists, it may be a bug that should be filed there, but we can talk here first to confirm.

**Comment by CQBB** [comment]
Hey thanks for your reply. I am not using the intelliJ plugin. Is the intelliJ plugin required to download the jar so that i can use in my project? I have set java_binary to depend on the artifact. I basically just use the java_maven example project.  BTW, i can not import the plugin b/c my intelliJ version is ahead what the current plugin version supports.

**Comment by CQBB** [comment]
Ok, i need to use IntelliJ plug in to download the jars. I spent several hours to figure it out. I didnt see anywhere in the doc says that the plugin is required....
