### ISSUE TITLE
Maven dependency references testonly override_targets

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_jvm_external#442]
Hi,

In my project, I am directly importing grpc-java with bazel and using `maven_install`. Since I'm using grpc-java directly, I've included `override_targets` so maven references to grpc get resolved to the bazel built version. This has been working well, however one of my maven dependencies is referencing `grpc-all`, which includes `grpc-testing`. This causes a problem because `@io_grpc_grpc_java//testing` is marked as `testonly`, but the maven dependency is not.

I've created a small repro of the problem [here](https://github.com/Dig-Doug/bazel_jvm_external_testonly).

Do you have any suggestions on how to fix this? I think this is really a problem with the library I'm using, so I'm going to try and fix it upstream. However, I was wondering if you had any other suggestions.

Thanks!

**Comment by btbuxton** [comment]
You could try to exclude grpc-testing from the maven dependency that brings in grpc-all. This can be done by the global excludes or you can do it at the artifact level.

I replaced 
"org.apache.beam:beam-runners-google-cloud-dataflow-java:2.21.0",

with:

maven.artifact(group = 'org.apache.beam', artifact = 'beam-runners-google-cloud-dataflow-java', version = '2.21.0', exclusions = ['io.grpc:grpc-testing']),

And it built with no errors.

You will need to also load:
load("@rules_jvm_external//:specs.bzl", "maven")

See artifact helper macro: https://github.com/bazelbuild/rules_jvm_external#artifact-helper-macro

Hope this helps.

**Comment by Dig-Doug** [comment]
That's the answer I was looking for, thanks!
