### ISSUE TITLE
Java export - publish to private google cloud storage bucket

### ISSUE THREAD

**Issue by zacharya19** [bazelbuild/rules_jvm_external#458]
Currently, the only way to publish a library is to local FS or HTTP site, so if you want to publish a private lib, you've to create a maven repo and grant access through user/password.
It will be nice to allow sending the files to GCS instead using application-default credentials, which will allow a quick private maven repo setup.
Also - if we do that, we should also support GCS as a source repo (should probably be a different issue).

Can take this issue on myself if we're up to support it, should be a simple change.

**Comment by jin** [comment]
cc @shs96c what do you think?

**Comment by shs96c** [comment]
Sounds like it might be useful for some folks. I'd be happy to review a PR and merge it in.
