### ISSUE TITLE
Error publishing to artifactory using java_export

### ISSUE THREAD

**Issue by EArbeitman** [bazelbuild/rules_jvm_external#476]
Hi,

I'm trying to use `java_export` but Im getting this error:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: Basic realm="Artifactory Realm"
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at rules.jvm.external.maven.MavenPublisher.main(MavenPublisher.java:82)
Caused by: java.lang.RuntimeException: Basic realm="Artifactory Realm"
        at rules.jvm.external.maven.MavenPublisher.lambda$httpUpload$1(MavenPublisher.java:186)
        at rules.jvm.external.maven.MavenPublisher.lambda$upload$0(MavenPublisher.java:154)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Here is my `java_export` target:

```

load("@bazel_common//tools/maven:pom_file.bzl", "pom_file")
load("@rules_jvm_external//:defs.bzl", "java_export")

java_export(
    name = "base",
    srcs = glob(["*.java"]),
    exports = [
        "//3rdparty:guava",
        "//3rdparty:jsr305",
        "//3rdparty:slf4j_api",
    ],
    deps = [
        "//3rdparty:guava",
        "//3rdparty:guice",
        "//3rdparty:joda_time",
        "//3rdparty:jsr305",
        "//3rdparty:slf4j_api",
        "//3rdparty:slf4j_jdk14",
    ],
    maven_coordinates = "com.example:0.0.1",
)

pom_file(
    name = "base_lib",
    targets = [
        ":base",
    ],
    template_file = "pom_template.xml",
)


```

Here is the command I ran:
```
 bazel run --define "maven_repo=https://my.jfrog.io/artifactory/maven-local" --define "maven_user=evan.arbeitman@compass.com" --define "maven_password=PASSWORD" //base:base.publish
```

The `Artifactory Realm` portion of the error is interesting. I wonder if its trying to pull credentials from my netrc file.

Thanks

**Comment by shs96c** [comment]
I'll have a look at this this week. I'm not sure why that's failing, but the error occurs when the request isn't authenticated. Perhaps a good first step in debugging this would be to add a better error message.

**Comment by EArbeitman** [comment]
> I'll have a look at this this week. I'm not sure why that's failing, but the error occurs when the request isn't authenticated. Perhaps a good first step in debugging this would be to add a better error message.

Thanks. One other question related to this: do you know if `gpg_sign=true` is required for publishing to external repos like artifactory?

**Comment by EArbeitman** [comment]
FWIW - I cloned this repo locally and then updated my project to use the local version of `java_export` instead of the remote version. Afterwards, I was able to publish to artifactory without an issue. Not sure why using the local version would be different. This is my code:


```
#Remote copy of repo:
http_archive(
    name = "rules_jvm_external",
    sha256 = "d85951a92c0908c80bd8551002d66cb23c3434409c814179c0ff026b53544dab",
    strip_prefix = "rules_jvm_external-3.3",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/3.3.zip",
)

# localy copy of repo
local_repository(
    name = "local_jvm_external",
    path = "/Users/evan.arbeitman/development/rules_jvm_external/",
)
#load("@rules_jvm_external//:defs.bzl", "java_export")
load("@local_jvm_external//:defs.bzl", "java_export")

```
@shs96c

**Comment by divanorama** [comment]
Could've been fixed by https://github.com/bazelbuild/rules_jvm_external/pull/452 which isn't part of 3.3

**Comment by jin** [comment]
Closing, will be making a new release soon.

**Comment by EArbeitman** [comment]
> http_archive(
>     name = "rules_jvm_external",
>     url = "https://github.com/bazelbuild/rules_jvm_external/archive/e22e6e3c5bbdf9ba4188a36de6a586242534af51.zip",
>     strip_prefix = "rules_jvm_external-e22e6e3c5bbdf9ba4188a36de6a586242534af51",
>     sha256 = "6e5d6b3019ad08d9b9443ffea34d64d37b1ee50abdc00e5c54ec19fcd8bb3b4e",
> )

hey @jin was curious if this patch is part of the 4.0 release? If not, any idea on when this will be released?

**Comment by divanorama** [comment]
I think it should be in 4.0 https://github.com/bazelbuild/rules_jvm_external/commits/4.0
But http_archive can be unreliable (anyone macro called from workspace can override it after it's defined in workspace, and even before in some cases)
- try `bazel query --output build //external:rules_jvm_external` (may still not show correct version https://github.com/bazelbuild/bazel/issues/12947)
- then try something like `bazel fetch //external:rules_jvm_external && echo "currently used rules_jvm_external code is in $(bazel info output_base)/external/rules_jvm_external"` and inspect the code there

**Comment by divanorama** [comment]
Also `bazel clean` or similar may help (netrc-related changes sometimes need an extra push to be propagated)
