### ISSUE TITLE
Release 4.0

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_jvm_external#493]
Tracking issue for release 4.0.

TODOs:

* [x] Identify remaining release blockers
* [x] Identify remaining open PRs to be rolled up into 4.0
* [x] Write/generate changelogs (with announcement that @cheister has joined the project as a committer 🎊)
* [x] Update README

cc @shs96c @cheister

**Comment by jin** [comment]
Tentative changelog:

`git log --oneline --no-merges `git describe --abbrev=0 --tags`..HEAD | cut -c 9- | sort`

- Add a provider to export the information being published (#439)
- Add @cheister to CODEOWNERS (#489)
- Add google cloud storage support to java_export (#463)
- Add @maven//:outdated to check for updated versions of artifacts (#465)
- Add pinning step to the simple example for user journey coverage (#427)
- Add regression test (#446)
- Adds a flag to fetch javadoc targets (#494) (#495)
- Add @shs96c to CODEOWNERS (#459)
- Bump bazel_toolchains to 3.5.0 (#461)
- Declare COURSIER_OPTS to make it available (#496)
- Export the MavenPublishInfo (#440)
- Fix compatibility with --incompatible_disable_depset_items (#431)
- Fix example BUILD: missing comma (#500)
- Fix jq path in :pin runnable (#454)
- Handle tags in java_export rule (#444)
- Introduce a deps and a setup macro (#481)
- Make @unpinned_maven//:pin always visible (#492)
- Only generate frames for versions of Java < 13 (#460)
- Output leading zeroes in maven export checksums (#453)
- Release 3.3 (#432)
- Remove digitialasset tests to fix CI.
- Remove unconditional registration of :android_platform for execution. (#456)
- Rework how maven project jars are calculated (#475)
- Spell auth scheme as "Basic" for artifactory (#452)
- Update coursier.bzl (#457)
- Update coursier to 2.0.7 for https://github.com/bazelbuild/rules_jvm_external/issues/471 (#482)
- Update documentation to use the latest names (#485)
- Update top-level description for RJE in the README. (#490)
- Use AddJarManifestEntry to add Target-Label to jars manifest (#468)
- Use BUILD instead of BUILD.bazel and buildifer these BUILD files (#470)
- Use JarHelper jar entry timestamp logic in MergeJars (#469)

**Comment by jin** [comment]
Proposing that #503 is the last release blocker to fix CI.

**Comment by cheister** [comment]
LGTM

**Comment by jin** [comment]
https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.0
