### ISSUE TITLE
add a flag to fetch javadoc for maven artifacts

### ISSUE THREAD

**Issue by erickj** [bazelbuild/rules_jvm_external#494]
just a feature request, that it would be nice to be able to use coursier's ability to fetch javadocs as additional artifacts. this requires additional support, similar to the `fetch_sources` flags because the underlying coursier command must be modified to use the `--javadoc` flag

**Comment by erickj** [comment]
created pull request https://github.com/bazelbuild/rules_jvm_external/pull/495/commits/6b7822a72532003a1c2bef6c01cb896369c7394a

**Comment by jin** [comment]
Merged in #495.
