### ISSUE TITLE
Fetching zip artifacts

### ISSUE THREAD

**Issue by connorworley** [bazelbuild/rules_jvm_external#501]
I'm dealing with a maven repo that serves .zip artifacts and I'm trying to fetch them using this rule:
```
load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        maven.artifact(
            group = "edu.wpi.first.wpiutil",
            artifact = "wpiutil-cpp",
            version = "2020.2.2",
            packaging = "zip",
            classifier = "headers",
        ),
    ],
    repositories = [
        "https://frcmaven.wpi.edu/artifactory/release",
    ],
)
```

My goal is to fetch https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/wpiutil/wpiutil-cpp/2020.2.2/wpiutil-cpp-2020.2.2-headers.zip, but when I build with `RJE_VERBOSE=true`, I see the rule is trying to fetch https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/wpiutil/wpiutil-cpp/2020.2.2/wpiutil-cpp-2020.2.2-headers.jar. Is there any way to support the former?

**Comment by cheister** [comment]
Seems like you would want to import those zip files with [http_archive](https://docs.bazel.build/versions/master/repo/http.html#http_archive) in the WORKSPACE instead?  

maven_install is primarily used to import jars and create `java_import` targets for them.

**Comment by connorworley** [comment]
That makes sense, I suppose I can interpolate the URLs myself.
