### ISSUE TITLE
PSA: Bintray and JCenter are being shut down on May 1st

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/rules_jvm_external#517]
Jcenter is being shut down on May 1st and the usages in this repo will need to be switched over to alternatives before May 1st

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by cheister** [comment]
Fixed with https://github.com/bazelbuild/rules_jvm_external/pull/523
