### ISSUE TITLE
java_export - Publish to private Amazon s3 bucket

### ISSUE THREAD

**Issue by rmrod** [bazelbuild/rules_jvm_external#545]
Currently java_export supports publishing a library to a local FS, HTTPS site or GCS.

It would be great if it were possible to publish to Amazon S3 buckets as well, using AWS default credentials.

I already did the code ([based on what was done for GSC](https://github.com/bazelbuild/rules_jvm_external/pull/463)), but would like to hear your thoughts on this.

Thank you.

**Comment by hisener** [comment]
Hey @rmrod, I have the same use case. Are you still willing to create a PR for this? If not, I can pick it up. 🙂
