### ISSUE TITLE
java_import invokes ijar, which clobbers inline functions in kotlin

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_jvm_external#59]
Given bazelbuild/bazel#4549, the maven repository workspace shouldn't use java_import, but should use something similar to kt_jvm_import which does the same thing, but offers the compile_jar as the same as the regular jar.  This will affect things like kotlin.test whose `assertFailsWith<ExceptionType>() { throw ExceptionType() }` inlines, and therefore needs the method bodies at compile-time.

**Comment by jin** [comment]
I'd prefer not to introduce a dependency on the Kotlin rules (for `kt_jvm_import`) for callers who are not using Kotlin. 

This can be implemented as a repository rule runtime check to generate `kt_jvm_import` for Kotlin-sourced JARs. Either that, or allow java_import to switch ijar off on a target basis.

**Comment by jin** [comment]
I took inspiration from your approach in https://github.com/square/bazel_maven_repository/issues/43 and https://github.com/square/bazel_maven_repository/pull/48, and adapted it for `coursier_fetch`'s BUILD file generation`. Thanks for that 😊 

Draft PR: https://github.com/bazelbuild/rules_jvm_external/pull/69

**Comment by cgruber** [comment]
My pleasure.  Just happy to get more people productive.
