### ISSUE TITLE
Update usage to include rules_jvm_external_setup

### ISSUE THREAD

**Issue by tsawada** [bazelbuild/rules_jvm_external#603]
After updating rules_jvm_external from 3.3 to 4.1, I noticed that following error occurs without `rules_jvm_external_setup()` call in my `WORKSPACE` file.

```
ERROR: .../external/rules_jvm_external/private/tools/java/rules/jvm/external/maven/BUILD:3:12: no such package '@rules_jvm_external_deps//': The
 repository '@rules_jvm_external_deps' could not be resolved and referenced by '@rules_jvm_external//private/tools/java/rules/jvm/external/maven:MavenPublisher'
```

It'd be great if the following snippet is included in the usage section of 4.0/4.1 releases. It is somewhat mentioned in the README.md, but that isn't complete (doesn't include `load()`s).

```
load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()
```

**Comment by asinbow** [comment]
Are `rules_jvm_external_deps()` and `rules_jvm_external_setup()` mandatory now?

**Comment by Jungle666** [comment]
I has one,is there any solution?

ERROR: /private/var/tmp/_bazel_jungleliu/a8b59b0ef5acb8878267e2a1b84d46f4/external/rules_jvm_external/private/tools/java/rules/jvm/external/maven/BUILD:3:12: no such package '@rules_jvm_external_deps//': The repository '@rules_jvm_external_deps' could not be resolved and referenced by '@rules_jvm_external//private/tools/java/rules/jvm/external/maven:MavenPublisher'
E

**Comment by shs96c** [comment]
I've updated the instructions in the releases. I've also created #641 that updates the README. Thank you for catching this, and thanks for the reminder to update things!
