### ISSUE TITLE
examples/spring_boot references vulnerable log4j version

### ISSUE THREAD

**Issue by philwo** [bazelbuild/rules_jvm_external#630]
Hi,

I'm going through all of bazelbuild's code and found that [examples/spring_boot/maven_install.json](https://github.com/bazelbuild/rules_jvm_external/blob/fa73b1a8e4846cee88240d0019b8f80d39feb1c3/examples/spring_boot/maven_install.json#L319) references a vulnerable version of log4j.

I know that it's just example code, but I think it would still be good to update this to the latest version. Unfortunately I don't know how to regenerate the JSON file with newer versions. Could you please look at this?

Thanks,
Philipp

**Comment by philwo** [comment]
We should also update [regression_testing_install.json](https://github.com/bazelbuild/rules_jvm_external/blob/73a1bc73b1758732de9f7a1ed3b1b349405f7f18/tests/custom_maven_install/regression_testing_install.json#L2934).

**Comment by jin** [comment]
Sent the PR. For the record, the steps are to:

1) Update the maven_install definition in the WORKSPACE file with the new version, and using `version_conflict_policy = "pinned"` to tell Coursier to use the explicit versions specified.
2) Run `bazel run @unpinned_maven//:pin`. This is documented here: https://github.com/bazelbuild/rules_jvm_external#updating-maven_installjson

**Comment by philwo** [comment]
Thanks!
