### ISSUE TITLE
mergejars doesn't create directory entries

### ISSUE THREAD

**Issue by simonlei** [bazelbuild/rules_jvm_external#643]
When I use java_export to create a jar and export it to maven, the merged jar will drop the directory entries like:

![image](https://user-images.githubusercontent.com/2107131/147450435-9a9ae69d-591f-4a0d-a9e2-3afcc8a02ebb.png)

The exported jar file has the directory entries:

![image](https://user-images.githubusercontent.com/2107131/147450960-096279a0-1b63-4f7c-ab88-ca767836f512.png)

Then if I use the merged jar file in spring, it can not scan components in the jar file because spring use classloader's
getResource("com/tencent/techmap") to match components (see PathMatchingResourcePatternResolver.java method doFindAllClassPathResources). That means the jar file published to maven cannot be used in spring.

**Comment by shs96c** [comment]
I believe that this was fixed by 0fe5ce5b40900fc8ed8fb11ec977abce3c18c564. Can you please verify that this works for you by using the HEAD version `rules_jvm_external` ? If it does, I shall close this issue.

**Comment by simonlei** [comment]
I tried the HEAD version of rules_jvm_external, it works, thanks very much.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/2107131/154878221-e856fbe6-1a89-4c88-8885-bd362e086c0c.png">

**Comment by shs96c** [comment]
Great news. Thank you for letting me know!
