### ISSUE TITLE
Error downloading, Checksum changed for 4.2 release

### ISSUE THREAD

**Issue by stamak** [bazelbuild/rules_jvm_external#665]
```
Error downloading [https://github.com/bazelbuild/rules_jvm_external/archive/4.2.zip] to 
/home/ci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/external/rules_jvm_external/temp16198115831920643553/4.2.zip: 
Checksum was e34ff633e6b8ea44c4f911b15b28079b17968694e2caa57b369c754208c16e4d but wanted
cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca
```

According to [release](https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.2) the correct is
```
RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"
```

**Comment by welshm** [comment]
Experiencing the same issue

**Comment by welshm** [comment]
Very relevant: https://twitter.com/shs96c/status/1488480089700503558?s=20&t=7sN01pOm0MzV2l8lfQmUDA

Hopefully this will resolve itself over time

**Comment by spew** [comment]
We are seeing this issue for the 3.0 release.

**Comment by jin** [comment]
https://twitter.com/tgummerer/status/1488493440103030787 suggests that it's been rolled back. Can folks here confirm if the issue has been resolved?
