### ISSUE TITLE
Feature: override `jq` download URLs

### ISSUE THREAD

**Issue by luangong** [bazelbuild/rules_jvm_external#668]
Similar to #389 about `coursier`, download URLs for `jq` are currently hardcoded as [https://github.com/stedolan/jq/releases/download/jq-1.6/jq-\<platform\>](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-<platform>). What’s different is that there are three URLs to override, one for each platform.

This might not always be possible due to corporate proxies etc. The possibility to override these download URLs would be nice.

**Comment by emidln-imc** [comment]
I believe you can configure the bazel downloader to rewrite the jq downloads to an internal URL. See this commit for details: https://github.com/bazelbuild/bazel/pull/12170

**Comment by luangong** [comment]
@emidln-imc Thanks for the info. I’m aware that there is a [`--distdir`](https://bazel.build/reference/command-line-reference#flag--distdir) flag and a [`--experimental_remote_downloader`](https://bazel.build/reference/command-line-reference#flag--experimental_remote_downloader) flag but I didn’t know there is also the [`--experimental_downloader_config`](https://bazel.build/reference/command-line-reference#flag--experimental_downloader_config) flag. Although not an ideal solution to rewrite all HTTP requests (e.g., it doesn’t affect the downloading of JARs from Maven Central with [Coursier](https://get-coursier.io/) from [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external), but a local repository can be specified), it does make it possible for building offline in an air-gapped environment.

P.S.: The flag has been renamed from `--experimental_remote_downloader_config` to `--experimental_downloader_config`.
