### ISSUE TITLE
java_export should not generate publisher script with credentials in it

### ISSUE THREAD

**Issue by dr-dime** [bazelbuild/rules_jvm_external#679]
credentials should be kept in

- files that are read-only to the current user or 
- in memory.

The current design of `_maven_publish_impl` will generate a file with
credentials in it and the file will be uploaded to the remote cache,
thus made available for anyone who has access to it.

All these credentials should be passed at the run time of the script,
not the build time, ie. `bazel run pkg.publish -- --user=x --password=y`
and more preferably from a maven config file, eg. `.m2/settings.xml`.

Relevant topics:

- bazelbuild/bazel#498
- #80

**Comment by sluongng** [comment]
@jin @shs96c We have a user asking about this on our end as well. It seems like the current implementation of `maven_export` and `maven_publish` would leak the password as plain-text onto the bash script artifact. This is, by default, an anti-pattern for most organizations to store credentials inside a build artifact.

When misuse happens, users would need to go through a painful process to purge the artifact from the remote cache and subsequent build/client machines.

Is it possible to provide a more sane default for maven library release process?

**Comment by shs96c** [comment]
I am happy to review a patch for this, as right now I've not got a huge amount of time to focus on this feature, even though it sounds like a very good idea.
