### ISSUE TITLE
linux-aarch64 (arm64) not supported

### ISSUE THREAD

**Issue by nresare** [bazelbuild/rules_jvm_external#728]
A project using the latest released version of rules_jvm_external (4.2) does not work at all on linux-aarch64, an increasingly common platform due to Docker on Apple silicon macs and Amazon's graviton offering.

There is a [change](https://github.com/bazelbuild/rules_jvm_external/pull/661) in latest master that enables basic functionality by simply pointing the jq version resolution to the x86_64 version for both mainstream linux platforms, even though that version normally will not execute on aarch64. This breaks the `:pin` functionality.

Taking a step back though, it seems to me like depending on the jq binary has some drawbacks. The upstream project is not moving very fast, and not publishing official binaries for a few of the common platforms we would like to support.

Would it make sense to re-implement the fairly trivial json transform in java and ship the jar somewhere (as the ability to run coursier depends on a working jvm)?

**Comment by shs96c** [comment]
How does it fail? I've not got ready access to a linux-aarch64 machine. Some more information would make this easier to understand and fix.

**Comment by nresare** [comment]
Apologies for the confusion, I am learning a new keyboard layout and accidentally hit enter, prematurely creating this issue. I'll add more details soon

**Comment by nresare** [comment]
in trying to isolate the problems I experienced, it seems the problem was elsewhere in my setup. Apologies for the noise
