### ISSUE TITLE
`AddJarManifestEntry` output differs based on local time zone

### ISSUE THREAD

**Issue by lukaciko** [bazelbuild/rules_jvm_external#735]
While investigating remote cache misses I found out that the hash of `header_<>.jar` files differed between what I had locally and what was on the remote agent, even though the JAR files from which these were generated was the same.

When comparing the JAR files using `zipinfo -v` I saw the modification times in the input JAR were:

```
file last modified on (DOS date/time):          2020 Jul 20 18:41:22
file last modified on (UT extra field modtime): 2020 Jul 21 03:41:22 local
file last modified on (UT extra field modtime): 2020 Jul 21 01:41:22 UTC
```

the local `header_` JAR has generated from the previous input has:

```
file last modified on (DOS date/time):          2020 Jul 21 03:41:22
file last modified on (UT extra field modtime): 2020 Jul 21 03:41:22 local
file last modified on (UT extra field modtime): 2020 Jul 21 01:41:22 UTC
```

and the remote `header_` JAR has:

```
file last modified on (DOS date/time):          2020 Jul 21 01:41:22
file last modified on (UT extra field modtime): 2020 Jul 21 03:41:22 local
file last modified on (UT extra field modtime): 2020 Jul 21 01:41:22 UTC
```

ZIP files encode the ancient MS-DOS time format, which represents "local" time and has no time zone information. An `extended timestamp` extra field (ID `0x5455`) can be used to encode the UTC time. You can ignore the lines ending with `local` in the examples above, that's not actually encoded, just the extra field printed based on my local time.

It looks like the MS-DOS time can differ based on the local time zone. I believe the issue happens here:

https://github.com/bazelbuild/rules_jvm_external/blob/8a9bcd940e441b9478ac82b8ac04ab85ed25758c/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry.java#L209

(The unzipped contents of both JAR files are the same, including the modification time stamps. The MS-DOS time stamps are ignored by at least my `unzip` implementation.)

This issue is similar to e.g. https://github.com/bazelbuild/bazel/pull/10976.

**Comment by shs96c** [comment]
Well, that's embarrassing. Thank you for raising the issue, and pin-pointing where the problem is :) The fix shouldn't be too hard to implement.

**Comment by lukaciko** [comment]
@shs96c I took a stab at fixing the issue and it was a bit cumbersome dealing with the `ZipEntry` API. Maybe there's a simpler way like setting up the timezone flag on the action.
