### ISSUE TITLE
rules_jvm_external broken with Bazel@HEAD in Bazel downstream pipeline

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_jvm_external#800]
Context: https://github.com/bazelbuild/bazel/issues/16746

Some tests in rules_jvm_external seem to parse the output log of Bazel and https://github.com/bazelbuild/bazel/commit/6e945e8ab422ca0a195d09899cce61ba6c0cfa59 broke the tests, please help resolve this issue so that we can make sure rules_jvm_external is green in [Bazel downstream pipeline](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2760) and keep detecting breaking changes/Bazel bugs that break rules_jvm_external

**Comment by cheister** [comment]
I think https://github.com/bazelbuild/rules_jvm_external/pull/803 should fix this issue, but I didn't know of an easy way to test it with bazel@head.

**Comment by meteorcloudy** [comment]
You can test with Bazel@HEAD by setting `bazel: last_green` in https://github.com/bazelbuild/rules_jvm_external/blob/master/.bazelci/presubmit.yml in your PR.

For example, in rules_apple's [presubmit.yml file](https://github.com/bazelbuild/rules_apple/blob/master/.bazelci/presubmit.yml#L20)

Check Bazel CI documentation: https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#using-a-specific-version-of-bazel

Of course, you can revert the change to keep testing with the latest Bazel release.
