### ISSUE TITLE
Document workflow for editing maven dependency

### ISSUE THREAD

**Issue by reddaly** [bazelbuild/rules_jvm_external#814]
What is the typical workflow for editing the source of a library that is typically provided through Maven? Could this be documented?

Suppose I find a bug in a library. I'm not sure how to fix it and change my bazel config to use the fixed version.

The library I'm interested in is https://github.com/bcdev/jzarr. I would prefer to load it from a forked git repository if possible.

**Comment by shs96c** [comment]
In this case, `rules_jvm_external` is pulling down the jars from Maven Central (or whichever repository you've configured in your build rules), so the way to contribute to them is the same as it is for any other third party dependency: find the repository that the dependency is from (which you've already done!), and then create a PR for them.

Once the PR is accepted, and a new release is made, update the dependency in your `maven_install` rule, and you'll have the new version.

**Comment by shs96c** [comment]
Since this is the normal way of updating third-party libraries (even if you're not using Bazel :) ), I'm not sure it's worth documenting this.
