### ISSUE TITLE
Release `rules_jvm_external` 5.0

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_jvm_external#831]
There are going to be some big changes coming in the next release, so the major version will be bumped. Tasks left to complete:

- [x] Add new lock file format #822 
- [x] When running `outdated` only suggest released versions #830 
- [x] Refactoring and restructuring of code
- [x] Bump `coursier` to the latest release
- [x] Merge https://github.com/bazelbuild/rules_jvm_external/pull/863 to fix proxy issue after updating coursier.

**Comment by cheister** [comment]
- [] Merge https://github.com/bazelbuild/rules_jvm_external/pull/863 to fix proxy issue after updating coursier.

**Comment by shs96c** [comment]
5.0 is out!

**Comment by BenHenning** [comment]
Thanks! As a heads up, I think the checksum for 5.1 on the releases page is incorrect (it seems to be the same as 5.0, but it should actually specify ``c4cd0fd413b43785494b986fdfeec5bb47eddca196af5a2a98061faab83ed7b2``).

**Comment by BenHenning** [comment]
> Please check that you're downloading from the correct URL, which is [given on the release page](https://github.com/bazelbuild/rules_jvm_external/releases/tag/5.1): https://github.com/bazelbuild/rules_jvm_external/releases/download/5.1/rules_jvm_external-5.1.tar.gz
> 
> We're now uploading artifacts to the releases rather than relying on GitHub's generated archives.

Ah to clarify, I was referring to the RULES_JVM_EXTERNAL_SHA that's listed on the release page for 5.1. It seems _that_ SHA hash isn't correct for the 5.1 archive that's downloaded per the URL in the provided rules_jvm_external target.

**Comment by shs96c** [comment]
`curl -L https://github.com/bazelbuild/rules_jvm_external/releases/download/5.1/rules_jvm_external-5.1.tar.gz | shasum -a256` gives `8c3b207722e5f97f1c83311582a6c11df99226e65e2471086e296561e57cc954` The shasum on the 5.1 release page is correct.

Previous releases have used GitHub's auto-generated archives, where the stanza used to load the ruleset was something like:

```
http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/refs/tags/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)
```

If you're just updating version numbers and shasums from those older releases, the shasum won't match. The new stanza reads:

```
http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/%s/rules_jvm_external-%s.tar.gz" % (RULES_JVM_EXTERNAL_TAG, RULES_JVM_EXTERNAL_TAG)
)
```

The URLs are similar, but different.

**Comment by shs96c** [comment]
Sure enough `curl -L https://github.com/bazelbuild/rules_jvm_external/archive/refs/tags/5.1.zip | shasum -a256` gives the same sha256 you reported: `c4cd0fd413b43785494b986fdfeec5bb47eddca196af5a2a98061faab83ed7b2`. You need to update the URL you're downloading the ruleset from :)
