### ISSUE TITLE
Does unpinned_maven throw away existing pinning?

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_jvm_external#837]
In other languages like Python, we take care that the operation required for "add a new dependency" doesn't accidentally pick up the newest version of *all* dependencies. The https://github.com/bazelbuild/rules_python/blob/main/docs/pip.md#compile_pip_requirements rule takes the currently pinned ("compiled") requirements as an input, and these are re-used when resolving dependencies, so they are stable even as new dependencies are added.

I didn't verify this, but since the repository is named "unpinned" it sounds like the re-pinning operation in rules_jvm_external will lose the current resolved dependency versions.

**Comment by jin** [comment]
It's a brand new coursier run, and doesn't reference the existing lockfile. In practice this may result in changed dependencies on the maven repo side if mutations were done.

**Comment by alexeagle** [comment]
I guess I'll have to study coursier docs to understand if it's able to use existing resolved constraints as an input to its version resolution process.

**Comment by shs96c** [comment]
`coursier` does not use previous resolutions as inputs to later dependency resolutions. We have, however, landed a new lock file format which aims to be more stable as dependencies are updated.
