### ISSUE TITLE
Flag --incompatible_python_disable_py2 will break rules_jvm_external in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/rules_jvm_external#846]
Incompatible flag `--incompatible_python_disable_py2` will be enabled by default in the next major release (Bazel 7.0), thus breaking rules_jvm_external. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17293](https://github.com/bazelbuild/bazel/issues/17293).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1408#0185f0c4-8fc6-40a4-a084-48d208a70b22)
- [Windows 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1408#0185f0c4-8fc9-4241-a3d9-6b903060fab3)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by rickeylev** [comment]
This appears to be the cause: https://github.com/bazelbuild/rules_jvm_external/blob/master/examples/android_instrumentation_test/.bazelrc#L3

`build --host_force_python=PY2` in examples/android_instrumentation_test/.bazelrc
