### ISSUE TITLE
Top-level repository aliases and cross-workspace dependencies

### ISSUE THREAD

**Issue by Zetten** [bazelbuild/rules_jvm_external#85]
Quite a few projects in the Bazel ecosystem expect their java dependencies to be individually imported as repository rules in their own right, for example [grpc-java](https://github.com/grpc/grpc-java/blob/master/repositories.bzl) expects to find the top-level `@com_google_guava_guava//jar`, which is created via the built-in rule `jvm_maven_import_external` (from `jvm.bzl`).

In my current projects, I tend to have a (generated) bunch of `jvm_maven_import_external`/`java_import_external` targets which supply both my own targets as well as third-party ones like grpc-java. That is, I don't use the `grpc_java_repositories` function to import those dependencies; I just ensure that I provide a compatible version in the expected place.

With `rules_jvm_external` the paradigm is slightly different. Resolution is now to many targets within a single repository rule, i.e. `@com_google_guava_guava//jar` becomes `@maven//:com_google_guava_guava`. This of course means that the loaded grpc-java rules can't find their dependencies when I switch to these new rules. If the `grpc_java_repositories` function is called, it will create a second repository rule for things which may already be available in the `@maven` workspace, and may cause classpath collisions downstream later.

I can see clear advantages to the new rules, particularly that different versions of the same artifact can now be resolved in different repositories (`@maven//:foo_bar` != `@othermaven//:foo_bar`). Downstream classpath collisions are clearly still possible there, so to some extent this grpc-java issue is just the natural outcome of an assumption of top-level repository safety/unity.

But, it might be useful to generate these `@foo_bar` top-level repository aliases for consistency with the old-style patterns. At least until there is a more obvious solution for reuse of Java deps across a full workspace including external dependency workspaces. Maybe this exists already! I'd be happy to find a solution to this problem :)

The built-in Bazel options such as [shadowing](https://docs.bazel.build/versions/master/external.html#shadowing-dependencies) and binding are only apparently functional for an entire workspace, so can't be used to generically alias individual targets in either the source or the target workspaces, i.e. it's not possible to redirect the `@foo_bar//jar` generated by `java_import_external`, nor target the `@maven//:foo_bar` for a single artifact.

A couple of options:

1. Add a parameter to the `maven_install` rule to allow generation of an additional `repositories.bzl` file, containing a function which can be loaded to create new repository rules for some/all artifacts in the closure, mirroring the format generated by `java_import_external`.
2. Make it easier for downstream workspaces to do the above, by exposing the generated `@maven//:dep-tree.json` file.

I have a hacked-up version of the first one, but it feels a bit ugly so far. Is there any plan for a migration path between `java_import_external` and `maven_install`? If not, would a PR for either option above be useful?

**Comment by dkelmer** [comment]
@Zetten: We will explore migration paths but that will take longer and will require improvements in tooling around WORKSPACE files. 

In the time being, solution (1) sounds great and we'd be happy to look at a PR for that!

**Comment by jin** [comment]
I have a prototype for this. See https://github.com/bazelbuild/rules_jvm_external/pull/160
