### ISSUE TITLE
Passing Arguments to MavenPublisher

### ISSUE THREAD

**Issue by loganasherjones** [bazelbuild/rules_jvm_external#936]
I'm trying to publish to a private artifactory which requires a custom CA. Whenever I use `maven_publish` (via `java_export`). I get failures because the embedded java I'm using comes with its own CA that I cannot modify even with a `~/.bazelrc` that looks like the following:

```
startup --host_jvm_args=-Djavax.net.ssl.trustStore=/path/to/cacerts \
        --host_jvm_args=-Djavax.net.ssl.trustStorePassword=changeit 
```

I'm not sure why that doesn't work, but whenever I attempt to run the `.publish` target, it uses the bundled CA.

I was hoping to be able to do something like:

```
bazel run :exported_lib.publish -- --jvm_flag=-Djavax.net.ssl.trustStore=/path/to/cacerts
```

However, this doesn't work because args aren't passed through.

It's possible I'm just not doing something right, but I'd really like to be able to specify the CA I use when I'm publishing.

I'll open up a PR with a potential fix, and am open to feedback.

Thanks.

**Comment by loganasherjones** [comment]
Closed with #937

**Comment by tnek** [comment]
This doesn't seem to have worked for me - 

```
$ bazel run --define "maven_repo=https://my-custom-maven-repo" //target.publish -- --jvm_flag=-Djavax.net.ssl.trustStore=/Library/Java/JavaVirtualMachines/jdk-21.0.2.jdk/Contents/Home/lib/security/cacerts
```

Is there something else I"m missing to make this work?

**Comment by loganasherjones** [comment]
Just to close the loop on this, I was able to get this working with 6.1 and above via:

```
bazel run \
  --define "maven_repo=https://my-custom-maven-repo \
  //path/to/target.publish \
  -- \
  --wrapper_script_flag="--jvm_flag=-Djavax.net.ssl.trustStore=/path/to/truststore"
```
