### ISSUE TITLE
Add Windows netrc support?

### ISSUE THREAD

**Issue by benjamin-bader** [bazelbuild/rules_jvm_external#940]
We have an org-private Artifactory server that we're using with `rules_jvm_external`, and would like to standardize on `.netrc` files for providing credentials.  The problem, I've discovered, is that the [`get_home_netrc_contents`](https://github.com/bazelbuild/rules_jvm_external/blob/39dcd72d72769acee2f02b869843259683f346c3/coursier.bzl#L313) explicitly does not handle Windows.  It kind of makes sense given that the file is non-standard and comes from GNU, but some common tools ([git](https://stackoverflow.com/questions/6031214/git-how-to-use-netrc-file-on-windows-to-save-user-and-password) for example) have some kind of support for `_netrc` on Windows.

The usual algorithm for locating the file on Windows seems to be:
1. Look for a `HOME` environment variable
2. Failing that, find the `USERPROFILE` environment variable
3. Whichever is found, look for a file named `_netrc`

Would you be open to a PR that adds this support?

**Comment by bartoszpop** [comment]
This issue can be closed. .netrc is now supported on Windows machines. It should be placed in the directory pointed to by USERPROFILE.
