### ISSUE TITLE
maven_fetch javadoc artifacts are at default visibility

### ISSUE THREAD

**Issue by erickj** [bazelbuild/rules_jvm_external#942]
Due to https://github.com/bazelbuild/bazel/issues/13681 the BUILD file generated from maven fetch does not set default visiblity to public.  The `jvm_import` and `alias` rules manually set `visibility = //visibility:public` to compensate for this.

The javadoc filegroup does not set this however, making it impossible to access.

**Comment by cheister** [comment]
Fixed with https://github.com/bazelbuild/rules_jvm_external/pull/943
