### ISSUE TITLE
V2 lock file does not support pinning artifacts with a `groupId` that starts with `build.`

### ISSUE THREAD

**Issue by andrew-lockwood** [bazelbuild/rules_jvm_external#970]
When upgrading from v4.5 to v5.3 (and thus from lock file v1 to v2), `http.bzl` started throwing IOExceptions with the message `Directory not empty` whenever `build.buf.protoc-gen-validate:pgv-java-grpc` was included as a given targets dependency. After a bit of digging, the error seems to be due to setting  `downloaded_file_path` to [groupId as directory](https://maven.apache.org/repository/layout.html#maven2-repository-layout) when generating pinned dependencies:

```python
http_file(
    name = "build_buf_protoc_gen_validate_pgv_java_grpc_0_6_13",
    sha256 = "b74f3de8648ff9545cf22046eea784b8017bd4ad5409866c581400df4520f1dc",
    netrc = "../maven/netrc",
    urls = ["https://repo.maven.apache.org/maven2/build/buf/protoc-gen-validate/pgv-java-grpc/0.6.13/pgv-java-grpc-0.6.13.jar"],
    downloaded_file_path = "build/buf/protoc-gen-validate/pgv-java-grpc/0.6.13/pgv-java-grpc-0.6.13.jar",
)

# For reference, `http_file` tries to create the following internal directory structure
#
# build_buf_protoc_gen_validate_pgv_java_grpc_0_6_13/
# ├── file/
# │   ├── build/buf/protoc-gen-validate/pgv-java-grpc/0.6.13/pgv-java-grpc-0.6.13.jar
# │   └── BUILD
# └── WORKSPACE        
```

I currently have a patch that appends `v1` to `downloaded_file_path` in [coursier.bzl](https://github.com/bazelbuild/rules_jvm_external/blob/5.3/coursier.bzl) and that seems to resolve the issue. From what I can tell, the path inside `http_file` is purely an implementation detail and doesn't seem to leak any functionality elsewhere.  I'm willing to work on a PR and shepherd it through if that fix sounds good. 

```patch
diff --git a/coursier.bzl b/coursier.bzl
index 061b067..ebbfe16 100644
--- a/coursier.bzl
+++ b/coursier.bzl
@@ -463,7 +463,7 @@ def _pinned_coursier_fetch_impl(repository_ctx):
         http_files.append("        urls = %s," % repr(
             [remove_auth_from_url(url) for url in artifact["urls"]],
         ))
-        http_files.append("        downloaded_file_path = \"%s\"," % artifact["file"])
+        http_files.append("        downloaded_file_path = \"v1/%s\"," % artifact["file"])
         http_files.append("    )")

     http_files.extend(["maven_artifacts = [\n%s\n]" % (",\n".join(["    \"%s\"" % artifact for artifact in maven_artifacts]))])
```

Note: I haven't tested this anywhere else, but this seems to _only_ be an issue on [MacOS](https://en.wikipedia.org/wiki/Case_sensitivity#In_filesystems)

**Comment by cheister** [comment]
Fix with https://github.com/bazelbuild/rules_jvm_external/pull/1037
